### ISSUE TITLE
Include epi parameters as advanced option

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#102]
Maybe I missed it, but I can't see the epi parameters any more. These should be available but as an advanced option somewhere that opens a new panel.

**Comment by cliffckerr** [comment]
@sayers24 @deviozc tagging you too, I still don't seem to be able to assign you -- @lgeorge-idm are you able to?

**Comment by mfisher-idmod** [comment]
Isn't that this? 
![image](https://user-images.githubusercontent.com/37818827/79012422-1a12e200-7b1b-11ea-8d25-be93ec146c3c.png)

**Comment by deviozc** [comment]
Is there any action on this?
epi parameters are in advanced section.

**Comment by sayers24** [comment]
For discoverability, we could change the "Advanced" label to "Population/Epidemiology"

**Comment by lgeorge-idm** [comment]
Closing as there is no action needed on this.
