### ISSUE TITLE
Change "landing experience"

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#103]
Pretty much the only thing I don't totally love about the current design is the experience when you first load the page. Having the parameters panel open over the app makes me feel like I clicked on something accidentally. Not sure what the solution is, but I trust you guys to come up with one :)

**Comment by cliffckerr** [comment]
@sayers24 @deviozc

**Comment by lgeorge-idm** [comment]
@cliffckerr we could, on first load, have a quick introduction overlay that is dismissed. I've never done the guided tutorial on the front end before but that might be another option.

**Comment by sayers24** [comment]
That shouldn't be too hard with the modal component. We could have an animated gif of an example run through. It could also give a space for some legal notice like what neherlab has. @cliffckerr thoughts?

**Comment by ckerr-IDM** [comment]
Sounds good!

**Comment by lgeorge-idm** [comment]
@sayers24 , let's roll with your idea of the walkthrough gif. We'll have to wait until the changes on the UI settle a bit 😁.

**Comment by cliffckerr** [comment]
Actually @lgeorge-idm @sayers24 @deviozc I just had a thought:
* Start with side panel open
* Have it open _under_ the header
* Have it move the results div to the right & shrink rather than being on top of it

Thoughts? Would still be in favor of an unobtrusive "quick tour" on page load, but I think this would help too

**Comment by lgeorge-idm** [comment]
@deviozc , could you take this? Thanks!

**Comment by sayers24** [comment]
Do we want to revert the panel overlay experience?

**Comment by lgeorge-idm** [comment]
No, but I think having it not obscure the header and footer will make it feel less like you've missed a step.

**Comment by sayers24** [comment]
Cool. I can take that one

**Comment by lgeorge-idm** [comment]
Closed by #118
