### ISSUE TITLE
[UI]: Hide n_days from Advanced options which is missing label and is duplicated in app

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#104]
On the web app, in the Advanced slidedown, you're missing the label on n_days:

![image](https://user-images.githubusercontent.com/37818827/79012630-95749380-7b1b-11ea-8f50-b93af1a47f26.png)

**Comment by lgeorge-idm** [comment]
@deviozc , can you take this one? I think we should probably hide this field instead of having it in 2 places.

**Comment by mfisher-idmod** [comment]
> @deviozc , can you take this one? I think we should probably hide this field instead of having it in 2 places.

Yep, I would agree with that because you have it at the top. Will rename this issue.

**Comment by deviozc** [comment]
Yeah, it should be hidden. I'll fix this.

**Comment by cliffckerr** [comment]
Closed by #106
