### ISSUE TITLE
[UI] more valid error indicating you can only have 1 intervention for each intervention event

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#109]
If you try to add more than 1 social distancing intervention for example, it returns the scenarioError 'Please enter a valid day range' instead of a more meaningful error message that you can only have 1 social distancing intervention for the simulation. Not super necessary, low priority issue.

![image](https://user-images.githubusercontent.com/37818827/79027619-cd8ecd00-7b41-11ea-80f8-ba167bc8ec6c.png)

**Comment by lgeorge-idm** [comment]
@mfisher-idmod, you can have more than one social distancing intervention, but the date ranges cannot overlap.
I'll fix this now since this is low hanging fruit.
