### ISSUE TITLE
[UI] n_days validation not working

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#111]
1. Type "20000" for campaign days
2. Expected: it says "Please enter a number between 1 and 90"
3. Actual: it lets you do it, until it gets killed by the timeout

I think this commit is the issue, it removed the validation for this parameter: 10fb46f723a72122f35e435a072ac8bac24f354c

**Comment by deviozc** [comment]
Fixed in #115
