### ISSUE TITLE
devtests- dev_test_synthpops- tests are failing

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#112]
Several things wrong (trying to work through these)

- coavsim parameters defined in basebars dictionary are outdated
- popchoices list is outdated
- pop_size of 3000 is incompatible with synthpops

**Comment by cliffckerr** [comment]
That's ok, I think we can just delete this file -- @DMistry-IDM ?

**Comment by DMistry-IDM** [comment]
can you point me to the file that calls this?

**Comment by CWiswell-IDM** [comment]
File is in the linked pull request. I got partway through fixing it, but I don't think that I understand the synthpops stuff well enough to get the test working again.

**Comment by DMistry-IDM** [comment]
@cliffckerr go ahead and close if you're no longer using it and don't think it's necessary. I can't really tell where this is anyways.
