### ISSUE TITLE
CD pipeline

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#12]
Whenever we release, build, push and update pypi, assuming infra is ready we could also automatically deploy new version to Azure

**Comment by jules2689** [comment]
Once the infra is up, I can take a stab at this!

**Comment by cliffckerr** [comment]
Closed by Docker build

**Comment by jules2689** [comment]
I think, ideally, we could also build the covasim package and push to pypi.
Once Azure is up, we could also trigger a deploy there after the docker build

**Comment by ckerr-IDM** [comment]
Having worked on projects with both manual and automatic pypi deployment before, I definitely prefer manual!

**Comment by jules2689** [comment]
Ah ok, we could publish a latest "master" python package to github packages and label it with the sha?
