### ISSUE TITLE
Use country-specific household sizes

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#120]
- [ ] Get data from https://population.un.org/Household/index.html#/countries/840
- [ ] Ensure listed countries match existing country names, and if not, make a new `mapping` for them a la: https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/data/loaders.py
- [ ] If location is not None, use `hybrid` population type
- [ ] Set number of household contacts to the correct number, i.e. `pars['contacts']['h'] = value`

cc @robynstuart @RomeshA @DMistry-IDM

**Comment by cliffckerr** [comment]
From @hamelsmu :
```
import pandas as pd
url = 'https://population.un.org/household/exceldata/population_division_UN_Houseshold_Size_and_Composition_2019.xlsx'
df =pd.read_excel(url, sheet_name=3, skiprows=4)
```

**Comment by gwincr11** [comment]
@cliffckerr I started the household size work in #141 where should I set the pars in the sim and the hybrid pop type?
