### ISSUE TITLE
Automate UI build with Webpack

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#123]
### Goals

- Enables automated unit and integration testing
- Helps prevent regressions
- Better and more stable crossbrowser support
- Transparent dependency management

**Comment by lgeorge-idm** [comment]
### Goals

- Enables automated unit and integration testing
- Helps prevent regressions
- Better and more stable crossbrowser support
- Transparent dependency management

**Comment by cliffckerr** [comment]
Closing for now but we can reopen if we decide to do this refactor

**Comment by cliffckerr** [comment]
Reopening since seems to be the only way to support Edge

**Comment by cliffckerr** [comment]
Closing since was not the only way to support Edge :)
