### ISSUE TITLE
change_beta intervention- perform basic testing

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#129]
From @CWiswell-IDM :

1. Run a simulation that consumes the change_beta intervention and look at the outputs.
2. Run the same simulation without the change_beta intervention, and look at the outputs.
Expected: They should be meaningfully different (for example, if change_beta significantly lowers beta, there should be less infections in the first case than the second)
3. Ad-hoc test of intervention parameters

Looks good! Tests are in here, but I'm not ready to PR yet:
https://github.com/amath-idm/covasim/tree/unittest_interventions

**Comment by CWiswell-IDM** [comment]
Basically tested! 
test_brutal_change_beta_intervention: If you set beta to 0, no more infections occur
test_change_beta_days: If you give a list of days equal to a list of changes, the multipliers are applied on the days specified.
test_change_beta_multipliers: If you run a series of simulations with the only difference being the amount to which you change beta, you get less infections the lower beta is (at crude levels of 1.0, 0.8, 0.6, 0.4, 0.2, this isn't meant to be 0.4000 is less than 0.4001).

test_change_beta_layers: 

- For clustered and hybrid population types, it is possible to disable the contact layers one at a time. When all four contact layers are disabled, no more transmission occurs.
- For random population types, you may disable contact layer 'a', which has a similar (same?) effect as change beta without the layer parameter.

areas remaining to be explored:
- change beta with synthpops layers. This has been tested locally, but without synthpops being part of the covasim package this has to be kept seperate.
- multiplier effects of layering change beta without layers on top of change beta with layers, etc.
