### ISSUE TITLE
test_prob intervention- needs basic testing

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#130]
From @CWiswell-IDM :

The test_prob intervention should be basically tested. This consists of the following:

1. Find and execute a sample simulation that uses this intervention. Look at (store) the results.
2. Disable the intervention from that same simulation, and re-run. Look at (store) those results, and compare to the results from step 1. Verify that the difference is clear and predictable.
3. Perform ad-hoc testing of parameters / options of the intervention.

**Comment by CWiswell-IDM** [comment]
Oh! I've got these tests in a branch that is waiting to rebase off of develop

**Comment by CWiswell-IDM** [comment]
Basic testing complete. This intervention distributes tests of a specified sensitivity to a target population.

test_test_prob_perfect_symptomatic: Makes sure that if you specify a 1.0 probability of testing symptomatic agents, you get an equal number of diagnoses as the number of symptomatics at that timestep.
test_test_prob_sensitivity: Verifies that the number of diagnoses from a set of tests is pretty close to the sensitivity times the number of symptomatic people tested (given 1.0 probability of testing them)
test_test_prob_symptomatic_prob_of_test: Works like the sensitivity test, except sensitivity is 1.0 and the probability of testing a symptomatic person is swept.

Areas to be explored:
- asymptomatic probability
- the quarantine probability (symptomatic and asymptomatic)
- multiple probabilities.  For example, symptomatic (not quarantined), plus all quarantined
