### ISSUE TITLE
contact_tracing- basic testing needed

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#131]
From @CWiswell-IDM :

1. Run a sample / example simulation that consumes the contact_tracing intervention, and view the results.
2. Disable the contact_tracing from the simulation, and rerun. view the results again, and compare to the results from step 1. The difference should be clear and predictable (for example, if contact_tracing gets people tested more frequently, we should see more tests)
3. Ad-hoc testing of parameters / features of the contact tracing intervention.

**Comment by CWiswell-IDM** [comment]
Need help here. Mentioned this in #idm-github-microsoft here https://covid-idm.slack.com/archives/C0110GFNJ6A/p1586981199340400 but I don't see an obvious thing that I can verify with this intervention. @cliffckerr, anyone else?  I'll proceed with creating some sims that use it, but the tests won't have a lot of meaning until I can see what this does.  With the absence of other direction, I'll just run some sims and "see what happens," and look for something to measure.

**Comment by CWiswell-IDM** [comment]
Testing has verified that the intervention can be constructed and consumed by the sim. Working on additional testing that contact tracing at perfect quality for one layer can be combined with change_beta for the other layers to mimic perfect change beta behavior.

**Comment by CWiswell-IDM** [comment]
#185 Should allow me to close this with a clearer conscience. :)
