### ISSUE TITLE
Web app testing

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#132]
From @mfisher-idmod :

Testing of the refactored web app, including new features:

- Upload Data (xlsx and csv)
- Simulation / Population parameters
- Epidemiological Parameters
- Interventions
- Upload campaigns (json)
- Browser compatibility (Chrome, Firefox, Safari, Edge)

See [Test Plan Wiki page](https://wiki.idmod.org/display/EMOD/Covasim+Web+App+Test+Plan#CovasimWebAppTestPlan-FeatureTesting) for web app Test Plan.

**Comment by mfisher-idmod** [comment]
This has been completed. Test results in PDF in https://wiki.idmod.org/pages/viewpage.action?spaceKey=EMOD&title=Covasim+Web+App+Test+Plan.
