### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#136]
### Goals
- Allows for splitting up code which supports more collaboration
- Enables unit testing
- Reduce regression w/ transpile time errors 

Split from #123

**Comment by cliffckerr** [comment]
Closing for now but we can reopen if we decide to do this refactor

**Comment by cliffckerr** [comment]
Reopening since seems to be the only way to support Edge

**Comment by cliffckerr** [comment]
Closing since was not the only way to support Edge :)
