### ISSUE TITLE
Where does beta come from?

### ISSUE THREAD

**Issue by wpettine** [InstituteforDiseaseModeling/covasim#139]
Where does the beta value of 0.015 come from? Is that based on literature or a fit? How does it compare to the beta in SIR models? 

 In the parameters.py file beta is:

`[line 40]  pars['beta']         = 0.015 # Beta per symptomatic contact; absolute`

To interpret model behavior, some sort of explanation is needed.

**Comment by ckerr-IDM** [comment]
Thanks @wpettine -- we are working on writing a paper with the full Covasim methodology. We are as you can imagine completely snowed under with other requests, but we will release it as soon as possible.

**Comment by lgeorge-idm** [comment]
Closing for now @wpettine, since this will be addressed in the forthcoming paper.
