### ISSUE TITLE
CI system is broken right now

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#14]
Checkout action fails, probably after move from private repo

**Comment by jules2689** [comment]
These lines (https://github.com/InstituteforDiseaseModeling/covasim/blob/master/.github/workflows/ubuntu.yaml#L20-L24) indicate there's a personal access token in use to checkout InstituteforDiseaseModeling/synthpops, can we validate that there is a `GitHub_PAT` secret in `settings > secrets`?

**Comment by cliffckerr** [comment]
Closed by https://github.com/amath-idm/covasim/pull/239

**Comment by jules2689** [comment]
@cliffckerr I'm not sure if that is supposed to be public, but it's private right now 😄
