### ISSUE TITLE
Enable multiprocessing

### ISSUE THREAD

**Issue by vishal-wiai** [InstituteforDiseaseModeling/covasim#15]
Currently the simulation runs only on single core. Can we add multiprocessing to make use of more workers and run the simulation faster?

**Comment by inc0** [comment]
Yes, this is good change, one way to handle it was described in #7

**Comment by cliffckerr** [comment]
@vishal-wiai @inc0 this isn't quite true, see `run.py:multi_run()`. However could definitely be made more flexible, e.g. currently if you split a sim across multiple cores they can't talk to each other.

**Comment by ckerr-IDM** [comment]
Closing for now, can reopen for a specific proposal
