### ISSUE TITLE
CI- please add dependency log as an artifact to build action

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#159]
It would be useful if at the end of every CI installation, we could run a pip freeze command, output this to a text file, and persist it as a build artifact in some easily findable way. This would make regression failure investigation easier.

**Comment by celiot-IDM** [comment]
Who would do this?

**Comment by cliffckerr** [comment]
I can close for now...the CI does already include all this information in the logs:
https://github.com/amath-idm/covasim/pull/382/checks?check_run_id=597316906
Sure, pip freeze would be easier to digest but  the hard part is not checking two runs, it's knowing that you need to be looking at pip freeze for the bug!
