### ISSUE TITLE
Numba 0.49 is slow - don't update from 0.48

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#160]
Upgrading Numba from 0.48 to 0.49 makes np.random.choice() 5x slower, increasing sim initialization time by the same amount. Is there a fix? Test code here:

https://github.com/InstituteforDiseaseModeling/covasim/blob/master/tests/devtests/deprecated/choose_tests.py

Steps:
1. Install numba==0.48 and confirm you get the faster speed.
2. Install numba==0.49 and confirm you get the slower speed.
3. Refactor test code so numba 0.49 performance is comparable to 0.48.
4. Implement fix in:
https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/utils.py#L166

If it can't be fixed, raise an issue with Numba:
https://github.com/numba/numba

Workaround: just pin to numba==0.48 (already done).

**Comment by lgeorge-idm** [comment]
@cliffckerr, is this RC0 or RC1? Can we live with the slower runtime for now?

cc: @daniel-klein and @celiot-IDM

**Comment by cliffckerr** [comment]
@lgeorge-idm neither, we can just pin the version indefinitely

**Comment by celiot-IDM** [comment]
I agree: stick with 0.48 until a decent update (>0.49) comes along. (Confounding consideration: are there any features or security features in 0.49 that we need ASASP?)

**Comment by lgeorge-idm** [comment]
They did remove all the Python 2 code and now only support >= Python 3.6.

> Removal of all Python 2 related code and also updating the minimum supported Python version to 3.6, the minimum supported NumPy version to 1.15 and the minimum supported SciPy version to 1.0. (Stuart Archibald).

http://numba.pydata.org/numba-doc/latest/release-notes.html#version-0-49-0-apr-16-2020

**Comment by ckerr-IDM** [comment]
The hope of this issue is that someone can figure out a different call signature so we can use 0.49, with the speed of 0.48.

**Comment by cliffckerr** [comment]
No immediate takers so will move to backlog

**Comment by cliffckerr** [comment]
Not solved but closing for now since no takers
