### ISSUE TITLE
Convert GitHub checks to V2 checkout

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#165]
**Describe the bug**

PRs are failing checks on checkout of sources

**To reproduce**

No good way to repro. Usually happens when rerunning checks on a PR.
Example: https://github.com/InstituteforDiseaseModeling/covasim/pull/152/checks?check_run_id=596695102

**Additional context**

- Fixed bug in GitHub Actions - Checkout: https://github.com/actions/checkout/issues/23

**Comment by cliffckerr** [comment]
This was fixed at some point
