### ISSUE TITLE
Random populations fall over between 200k and 400k

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#167]
**Describe the bug**

Creating a random population at 200k works fine, gets constructed in about 15 seconds. 400k continued churning for 3 minutes. Probably worth putting a cap on here somewhere.

**To reproduce**

```python
import covasim as cv
pop_200k_one_day = {
    'pop_scale': 1,
    'n_days': 1,
    'pop_size': 2e5,
    'pop_infected': 0
}
sim = cv.Sim(pars=pop_200k_one_day) # Configure the simulation
sim.run() # Steps required to produce the behavior
```

**Expected behavior**

I eventually expected it to fall over. :) 1e6 sat there for 20 minutes (while I switched projects), I gave 400k 3 minutes before cancelling.

**Screenshots or outputs**

```
    self.run_sim(pop_400k_one_day)
  File "c:\GitHub\covasim\tests\unittests\unittest_support_classes.py", line 241, in run_sim
    self.sim.run(verbose=0)
  File "c:\github\covasim\covasim\sim.py", line 354, in run
    self.initialize()
  File "c:\github\covasim\covasim\sim.py", line 136, in initialize
    self.init_people(**kwargs) # Create all the people (slow)
  File "c:\github\covasim\covasim\sim.py", line 235, in init_people
    cvpop.make_people(self, verbose=verbose, **kwargs)
  File "c:\github\covasim\covasim\population.py", line 60, in make_people
    popdict = make_randpop(sim, microstructure=pop_type)
  File "c:\github\covasim\covasim\population.py", line 115, in make_randpop
    contacts, layer_keys = make_random_contacts(pop_size, sim['contacts'])
  File "c:\github\covasim\covasim\population.py", line 145, in make_random_contacts
    contact_dict[key] = cvu.choose(max_n=pop_size, n=n_contacts) # Choose people at random
KeyboardInterrupt
```

**Platform (please complete the following information):**
 - Covasim version: [e.g. 0.27.5]
 - OS: Win10

**Additional context**

Just trying to meet the request in #133

**Comment by ckerr-IDM** [comment]
This should only be RAM- and patience-limited :) Memory tests (https://github.com/InstituteforDiseaseModeling/covasim/blob/master/tests/devtests/archive/memory_test.py) show 500KB per 1000 people, so on a big VM with 500 GB RAM, you should be able to simulate...a billion people. I would not recommend it, but no need to raise an exception.

**Comment by ckerr-IDM** [comment]
@CWiswell-IDM For the record, 1e6 worked for me -- and only took 3% of my laptop's memory!
```
>>> import sciris as sc
>>> import covasim as cv
Covasim 0.27.11 (2020-04-17) — © 2020 by IDM
>>> sim = cv.Sim(pop_size=1e6)
>>> sc.tic(); sim.initialize(); sc.toc()
1587187959.2373662
Initializing sim with 1e+06 people for 60 days
Elapsed time: 230 s
```

**Comment by ckerr-IDM** [comment]
Did a bit of refactoring. :)
```
>>> import sciris as sc
>>> import covasim as cv
Covasim 0.27.11 (2020-04-17) — © 2020 by IDM
>>> sim = cv.Sim(pop_size=1e6)
>>> sc.tic(); sim.initialize(); sc.toc()
1587191076.600737
Initializing sim with 1e+06 people for 60 days
Elapsed time: 12.7 s
```

**Comment by CWiswell-IDM** [comment]
... then increment the version!

**Comment by ckerr-IDM** [comment]
:) 
https://github.com/InstituteforDiseaseModeling/covasim/blob/master/tests/devtests/archive/memory_test2.py#L21

**Comment by CWiswell-IDM** [comment]
? https://github.com/InstituteforDiseaseModeling/covasim/blob/master/tests/devtests/archive/memory_test2.py#L37

**Comment by ckerr-IDM** [comment]
I incremented it after running that test and confirming it worked :) Will fix in the comment
