### ISSUE TITLE
Covasim user group feedback

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#172]
From David Wilson (Gates Foundation):
- [ ] Use more data and pre-loaded defaults
- [x] Show dates on x-axis
- [ ] Fix critical and rename hospital/ICU demand
- [ ] Have "Number of ventilators" as a model parameter with ability to change via an intervention

**Comment by wpettine** [comment]
1) Have "Number of ventilators" as a model parameter with ability to change via an intervention
2) Fix critical and rename hospital/ICU demand
3) Use more data and pre-loaded defaults
