### ISSUE TITLE
[UI] Data upload uncaught TypError for xlsx files

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#178]
**Describe the bug**

When you upload a xlsx file of epi data with "Upload data", it doesn't upload. In F12 developer console, you see:
cova_app.js:118 Uncaught (in promise) TypeError: onerror is not a function
    at cova_app.js:118

Testing Version 0.28.3 on Chrome, Firefox, and Safari.

**To reproduce**

_For UI issues:_
1. Save the tests\example_data.csv as a xlsx file
2. In the "Open configuration", select this xlsx file to upload
3. Select Run to run the simulation

xlsx file used uploaded here. 
[example_data_unedited.xlsx](https://github.com/InstituteforDiseaseModeling/covasim/files/4512146/example_data_unedited.xlsx)

**Expected behavior**

The xlsx file uploads and when you click run, it runs with the api data uploaded as well as the sim parameters set.

**Screenshots or outputs**

F12 Developer Tools shows the error on upload of the xlsx file and plots from sim run do not reflect the xslx data attempted to be uploaded.

![image](https://user-images.githubusercontent.com/37818827/79904123-098b2300-83c9-11ea-8c6b-e96f927ef7f8.png)

**Platform (please complete the following information):**
 - Covasim version: 0.28.3
 - OS: Windows
 - Browsers: Chrome, Firefox, Safari

**Comment by cliffckerr** [comment]
Fixed; this was due to `upload_file()` trying to parse the file:
```

@app.register_RPC(call_type='upload')
def upload_file(file):
    stem, ext = os.path.splitext(file)
    data = sc.loadtext(file)
    fd, path = tempfile.mkstemp(suffix=ext, prefix="input_", dir=tempfile.mkdtemp())
    with open(path, mode='w', encoding="utf-8", newline="\n") as fd:
        fd.write(data)
        fd.flush()
        fd.close()
    return path
```
The solution is to just copy it to a temp folder and return the path and let Covasim parse it:
```
@app.register_RPC(call_type='upload')
def upload_file(file):
    stem, ext = os.path.splitext(file)
    fd, path = tempfile.mkstemp(suffix=ext, prefix="input_", dir=tempfile.mkdtemp())
    sh.copyfile(file, path)
    return path
```

**Comment by cliffckerr** [comment]
Example data file attached
[example_data.xlsx](https://github.com/InstituteforDiseaseModeling/covasim/files/4514288/example_data.xlsx)

**Comment by mfisher-idmod** [comment]
Verified fixed in RC0.
