### ISSUE TITLE
Webapp refactor

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#180]
From @lgeorge-idm , relating to https://github.com/InstituteforDiseaseModeling/covasim/pull/171:

- [ ] Fix `<img src="assets/idm-logo.png" height="30px"/>`
The class is 'img-fluid'. You should also add in cova_app.css a max-height for the footer images of 2em and make sure the text aligns properly.

- [ ] Overriding the nav-text class and adding the spans is unnecessary. Instead, just override the nav-link class.

- [ ] Please use the {{app.github_url}} tokens instead of hard-coded links.

- [ ] Merge parheader and card-header class.

- [ ] Revisit font for webapp: Quicksand is hard to read on non-Ultra HD monitors. Please pick another font or choose a heavier default weight.

**Comment by mfisher-idmod** [comment]
Adding comments from PR #171 - 

- [ ] Revisit font for webapp
Quicksand is hard to read on non-Ultra HD monitors. Please pick another font or choose a heavier default weight.

**Comment by cliffckerr** [comment]
Closed by #200
