### ISSUE TITLE
[UI] Support for Edge 

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/covasim#184]
**Describe the bug**

This issue is to be addressed later, not now. Currently, the web app doesn't load properly in Edge. See screenshot.

**To reproduce**

_For UI issues:_
1. Open up Edge
2. Navigate to the covasim app in the browser

**Expected behavior**

Web app loads without issues in Edge

**Screenshots or outputs**

![image](https://user-images.githubusercontent.com/37818827/80043738-65cc7080-84b7-11ea-98f2-09203f338698.png)

**Platform (please complete the following information):**
 - Covasim version: 0.28.5
 - OS: Windows
 - Browser: Edge

**Comment by cliffckerr** [comment]
Seems like Vue is just not rendering at all...

**Comment by cliffckerr** [comment]
@mfisher-idmod Are there any console errors? Does Edge have a console? :stuck_out_tongue:

**Comment by cliffckerr** [comment]
If it's not a quick fix, would suggest a user agent check and then "Please use Chrome or Firefox to use the Covasim app".

**Comment by mfisher-idmod** [comment]
@cliffckerr Console errors from Edge for target _top: sim 

![image](https://user-images.githubusercontent.com/37818827/80155384-7bed3600-8576-11ea-8f61-d1f543729ad8.png)

For "SCRIPT1028: SCRIPT1028: Expected identifier, string or number". Looks like it's this issue: https://github.com/vuetifyjs/vuetify/issues/8279

I'd be ok with the user agent check and message, if we were to deal with Edge later for government employees who still use IE/Edge.

**Comment by lgeorge-idm** [comment]
This is a one line fix.
