### ISSUE TITLE
Update DNS URL to covasim.idmod.org with HTTPS Support

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#193]
Reproducing slack chat:
> @celiot-IDM
> HTTPS support has come up as an issue recently. For example, our DOD partners using locked-down browsers can't get to idmod.org. So let's plan to have https support from the start.
> 
> @cliffckerr   17:23
> Would it be possible to have covasim.idmod.org? VOI stands for "value of information" and is for a completely different model and I just used that because it was the only DNS I had access to 
>
> @John-Sheppard   17:31
> We could.  I'll check with ITOPS on the availability.  I thought that is what you wanted to use the whole time so I didn't pursue anything different.

**Comment by cliffckerr** [comment]
Working: https://covasim.idmod.org/
