### ISSUE TITLE
UI layout updates

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#201]
Some suggested UI updates, comparing previous (L) and current (R) versions:
- [x] Model parameters should be open by default
- [ ] "Run" button should be visible at bottom of the left sidebar even when sections are open
- [ ] For narrow screens, sidebar should be wider -- resumably with wide screens users would want to see both at the same time, but for narrow screens they'd switch back and forth
- [ ] Might feel more app-like and less like a webpage if header and footer were always visible (then again, it does waste screen real estate)

If the header and footer persisted (i.e. the scrolling happened inside the graphs div instead), then something like the previous sidebar layout might be workable. The sidebar and the graphs should scroll independently since you might want to keep looking at a graph as you adjust the parameters.

![image](https://user-images.githubusercontent.com/3239256/80273886-1048bd00-868b-11ea-9bad-223147026bac.png)

**Comment by cliffckerr** [comment]
E.g. the UX here would be improved by being able to see both the run button and the graphs:
![image](https://user-images.githubusercontent.com/3239256/80274053-86015880-868c-11ea-8570-e8729a35d1ca.png)

**Comment by lgeorge-idm** [comment]
Blocked by #202 and #194.

**Comment by cliffckerr** [comment]
Closing for now since UI needs major overhaul
