### ISSUE TITLE
Redo intervention UI

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#202]
Feedback from @daniel-klein : "Also in interventions - there's 4 separate list (by tab) of current interventions.  Better would be if one master list to see all at once or at least to click on the timeline and be able to see/edit/delete."

Suggestion: don't really need to have multiple instances of each intervention, so have them be rows instead of tabs, e.g. something like: 
![image](https://user-images.githubusercontent.com/3239256/80274663-f27e5680-8690-11ea-9e78-280d8740dd68.png)

Also from Dan: "In the interventions, it's not clear what we're assuming - what does "Moderate effectiveness" mean?  "Contact tracing" is essentially useless because we have no clue what it's doing." Should include tool tips for these.

**Comment by cliffckerr** [comment]
On second thought, let's just let the user enter their own values:
![image](https://user-images.githubusercontent.com/3239256/80288054-25086d80-86ea-11ea-83df-bb069e16e2c4.png)

**Comment by lgeorge-idm** [comment]
@cliffckerr I can start on this tomorrow.

**Comment by cliffckerr** [comment]
Thank you @lgeorge-idm !

**Comment by lgeorge-idm** [comment]
Here is the static table variant of the UI:
![image](https://user-images.githubusercontent.com/43424134/80519779-5b89f680-893d-11ea-9db1-ccf4fadd65b6.png)

**Comment by lgeorge-idm** [comment]
Split off the conversion to singular list here: #212
