### ISSUE TITLE
sim.to_json should create a representation of interventions without a warning

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#205]
If you call the to_json() method on a sim that has an intervention in it, the sim writes a warning to screen about the inability to serialize the intervention. This clogs up the console in a simulation with more than a few interventions.

Saw this while regressing a ticket with intervention unit tests. What you see below is the console output of looping over 20 random number seeds. I got this for each of the 20 sims and it made the results of each sim hard to see.

```
Initializing sim with 5000 people for 60 days
Could not sanitize "<covasim.interventions.change_beta object at 0x000001E81C68D470>" <class 'covasim.interventions.change_beta'> (Object of type 'change_beta' is not JSON serializable), converting to string instead
Could not sanitize "<covasim.interventions.change_beta object at 0x000001E81C68D710>" <class 'covasim.interventions.change_beta'> (Object of type 'change_beta' is not JSON serializable), converting to string instead
Could not sanitize "<covasim.interventions.change_beta object at 0x000001E81C68DEB8>" <class 'covasim.interventions.change_beta'> (Object of type 'change_beta' is not JSON serializable), converting to string instead
Could not sanitize "<covasim.interventions.change_beta object at 0x000001E81C68D828>" <class 'covasim.interventions.change_beta'> (Object of type 'change_beta' is not JSON serializable), converting to string instead
ERROR: seed 19
        The cumulative infections at 45 should be the same as at the end.
```

Could this warning be suppressed? I'm not sure if you can construct these interventions by loading from json but if you can, I think the warning is unnecessary.

**Comment by cliffckerr** [comment]
Yes, this is a known issue -- will get to it eventually. Need to have both to and from json methods.

**Comment by cliffckerr** [comment]
Closed by :point_up:
