### ISSUE TITLE
Cannot locate synthpops package

### ISSUE THREAD

**Issue by neillbyrne** [InstituteforDiseaseModeling/covasim#209]
I cant seem to find the  synthpop**s** package. It doesnt seem to be available via pip,

`$ pip search synthpops` 
`py-synthpop (0.1.2)  - Python implementation of the R package synthpop`

nor is it listed on PyPI

![image](https://user-images.githubusercontent.com/12056335/80393396-5464d900-88a8-11ea-84ed-4d8edb3710f4.png)

**Comment by cliffckerr** [comment]
Hi @neillbyrne , synthpops is still under development. Please use a different population type, e.g. `hybrid`, until it is ready for release.
