### ISSUE TITLE
Receiving type error at runtime

### ISSUE THREAD

**Issue by laurelboyd** [InstituteforDiseaseModeling/covasim#21]
Hi -
After I set up the project I was able to run the first example, but not the second (python examples/run_sim.py) due to what looks like a data type mismatch. Because I didn't specify any data types in the code, I wonder if this is a bug?

See my command prompt code and log below:

```
(covasim) C:\Users\laurel\covasim>python examples/run_sim.py
Importing...
Covasim 0.22.0 (2020-03-31) — © 2020 by IDM
Note: synthpops (for detailed demographic data) is not available (No module named 'synthpops')

Elapsed time: 3.06 s
Making sim...
Running...
TEMP init people
  Creating 20000.0 people...
  Created 20000 people, average age 38.58 years
  Running day 0 of 60 (0.60 s elapsed)...
  Running day 1 of 60 (0.60 s elapsed)...
  Running day 2 of 60 (0.60 s elapsed)...
Traceback (most recent call last):
  File "examples/run_sim.py", line 35, in <module>
    sim.run(verbose=verbose)
  File "C:\Users\laurel\covasim\covasim\sim.py", line 396, in run
    transmission_inds = cvu.bf(thisbeta, person.contacts)
  File "C:\Users\laurel\covasim\lib\site-packages\numba-0.48.0-py3.8-win32.egg\numba\dispatcher.py", line 574, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) float64, array(int32, 1d, C)
```

**Comment by krosenfeld-IDM** [comment]
Hi Lauren,

I'm not able to reproduce this error.  Could you give a few more details? How did you install? (virtual environment? Did you use pip or from source?).  Thanks!

**Comment by ckerr-IDM** [comment]
Not able to reproduce

**Comment by khmoud75** [comment]
I have the same error . I flow all steps ,but I can't run any example . the only example I can run is the first . any one can help me with this. this my first time with python .

**Comment by ckerr-IDM** [comment]
Hi @khmoud75  -- the model uses advanced Python features so if this is your first time using Python, it may be quite challenging to get up to speed. We recommend completing a scientific computing in Python online course first, e.g.:
https://scipy-lectures.org/
https://www.enthought.com/courses/python-for-scientists-and-engineers/

**Comment by khmoud75** [comment]
Hi @ckerr-IDM  thank you for your answer . yes I new with python, but I can learn fast. I get the below error message . I need find solution to it can you help me please? 
C:\Users\User\Downloads\covasim-master>python examples/run_sim.py
Importing...
Covasim 0.23.5 (2020-04-06) — © 2020 by IDM
Note: synthpops (for detailed demographic data) is not available (No module named 'synthpops')

Configuring...
Making sim...
Running...
  Creating 20000 people...
Traceback (most recent call last):
  File "examples/run_sim.py", line 43, in <module>
    sim.run(verbose=verbose)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\covasim\sim.py", line 436, in run
    self.initialize()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\covasim\sim.py", line 160, in initialize
    self.init_people(**kwargs) # Create all the people (slow)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\covasim\sim.py", line 264, in init_people
    cvppl.make_people(self, verbose=verbose, id_len=id_len, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\covasim\people.py", line 255, in make_people
    import synthpops as sp # Optional import
ModuleNotFoundError: No module named 'synthpops'

**Comment by ckerr-IDM** [comment]
Hi @khmoud75 -- please reinstall Covasim, I see you are using version 0.23.5 but the current version is 0.28.6. I suggest checking the documentation regularly for updates:
https://institutefordiseasemodeling.github.io/covasim-docs
