### ISSUE TITLE
examples with new syntax

### ISSUE THREAD

**Issue by kgustafs** [InstituteforDiseaseModeling/covasim#210]
The run_scenarios.py example seems to be out of date, which can easily happen when the code is evolving quickly like here. 

I am trying to run a set of scenarios and I find the tests more useful but there are extra components in the tests that may not be efficient nor necessary.

When debugging a custom script it is not for certain that mixing the examples/ syntax and the tests/ syntax is not causing a crash.

At best, it would be great to have examples that are up to date. At least, it would be great to know that the examples are compatible with new versions.

Thank you

**Comment by cliffckerr** [comment]
Thanks @kgustafs -- yes, we should update the examples! You can look in the tests folder for other examples for now.

**Comment by cliffckerr** [comment]
@kgustafs Merged last night, let me know what you think of the latest version!

**Comment by cliffckerr** [comment]
Closing for now -- @kgustafs please reopen if the issue hasn't been addressed in the latest version

**Comment by kgustafs** [comment]
Thanks @cliffckerr I've been able to find what I need in the tests and devtests, much appreciated.
