### ISSUE TITLE
Convert intervention tabs to singular list

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#212]
### Summary
This is split from #202. The request is to see all interventions in a single table as opposed to a tabbed interface.

### Suggested solution
- Use a dropdown to select the intervention type and then list the interventions in a tabular format
- Enables reusing existing code and requires minimal refactoring of the front end.

### Additional context
- Changing to to as static table requires changing the entire eventing model, validation model, and rendering.
First pass done here:
![image](https://user-images.githubusercontent.com/43424134/80519779-5b89f680-893d-11ea-9db1-ccf4fadd65b6.png)

**Comment by cliffckerr** [comment]
Now that Covasim has been publicly released, let's take a step back and scope this out a little more carefully.
