### ISSUE TITLE
WebApp: Tooltips for testing and tracing intervention should mention that people are isolated. 

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/covasim#222]
Covasim, WebApp, click to expand Interventions Bar, hover over the intervention tabs

Current descriptions for Testing and Tracing interventions are: 
"Testing rates for people with symptoms" and "Contact Tracing of diagnosed cases (requires testing intervention to be set)"
Nothing in this indicates how that reduces the spread. 
I propose to expand the descriptions to "Testing rates and, if found positive isolating, for people with symptoms" and "Contact tracing of diagnosed cases, those found positive are isolated (requires testing intervention to be set)"

**Comment by cliffckerr** [comment]
@Sv3tlana This is important, and we should think carefully how to approach this overall. Each intervention corresponds to several paragraphs in the methods section of the paper we're writing, which is probably too much for a tooltip. We probably need a "Further information" box or a ? button that opens up a proper modal with the full methodology. We should consider this as we're redoing the UI (cc @lgeorge-idm ).

**Comment by Sv3tlana** [comment]
Ok.

**Comment by lgeorge-idm** [comment]
@Sv3tlana , keep these issues coming though because clarity is really important in making the webapp useful.

**Comment by cliffckerr** [comment]
Closing for now since the UI needs a major overhaul

**Comment by Sv3tlana** [comment]
Could it be.. iced or something? To make these as "to do" items for the overhaul?

**Comment by cliffckerr** [comment]
@Sv3tlana Yes -- we'll see what ends up happening; we might start a separate repo for the webapp, and we might move away from the "one size fits all" approach and instead have the UI so users can upload and explore custom projects. But good idea, I'll add a label to keep these separate
