### ISSUE TITLE
Covasim>Webapp>Epi parameters tooltips need improvement/ don't make sense

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/covasim#223]
Covasim>Webapp>Model Parameters> look at the tooltips and default values:

Parameter: default value: tooltip descrition. 

Time to infectiousness(days): 4 : Average Number of days between exposure and being infectious
 -- This and "asymptomatic period" parameter below together as-is seem to indicate that a person develops symptoms 1 day after exposure, and then 3 more days later they become infectious?? So a person is symptomatic and not infectious for 3 days? That doesn't seem right. 

Asymptomatic period(days): 1 : Average Number of days between exposure and developing symptoms
 -- The Epi Parameters doc on the front page says it takes 4-5 and up to 11-2 days between infection and onset of symptoms. This seems to indicate it's 1 day?  My guess is this parameter is "Average Number of days after person becomes infectious before they develop symptoms", which would make 4 days until infectiousness and then 1 more days until symptoms, so a person is infectious and walking around without knowing it or having symptoms for one day (if they develop symptoms at all). 

Infection duration(days): 10 : Average Number of days between infection and recovery (viral shedding period)
-- in the Epi Parameters doc on front page, "infection" is used as "exposure" in the Incubation Period description ("It takes about 4-5 days, but could take up to 11-12 days, between infection and onset of symptoms"). If it's used the same here, we are indicating that person is infectious for 10 days after exposure? Does this mean to say "Infectious duration" and that it's an "average number of days between becoming infectious and recovery (viral shedding period)"

Time until death(days): 6: Average Number of days between becoming critically ill and death. 
---- I'm not sure what this parameter affects, but it's hard to connect it to anything since we don't know when a person becomes critically ill? is this a period for which person is sick and alive, but is self-isolated and not infecting others because they are critically ill? I'm not sure what this number affects and where.

**Comment by Sv3tlana** [comment]
@lgeorge-idm :)

**Comment by cliffckerr** [comment]
Thanks @Sv3tlana , will look into these -- once again, much of this is the inordinate complexity of the actual model bumping up against the reality of making a digestible UI. The durations, for example, are _actually_ Poisson draws of lognormal distributions controlled by 18 different parameters, so it's challenging to think of a way of giving the user some knobs they can meaningfully adjust without being overwhelming.

**Comment by cliffckerr** [comment]
Closing for now since the UI needs a major overhaul
