### ISSUE TITLE
[UI 2.0] Interface improvements

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#229]
Miscellaneous improvements to the interface to improve usability.

- [ ] Using dates rather than day numbers and allow the user to choose the start and end dates rather than days
- [ ] Rename severe/critical to hospitalized/ICU
- [ ] Add additional interventions, such as numbers of beds or ventilators
- [ ] Confirm changes with Users Group

**Comment by laurengulland** [comment]
Hi there -- I'm interested in contributing to this project if you're looking for help!

I was thinking that as a good entry point, I could take on that rename severe/critical to hospitalized/ICU. If that's something you're looking for, are you wanting that change made only in the UI, or in all references and variables throughout the app (or somewhere in the middle)?

**Comment by lgeorge-idm** [comment]
Hi @laurengulland , thank you so much for reaching out. We're in the process heavily redesigning some of the interface. Once that's done, it would be great to have more helping hands.

**Comment by laurengulland** [comment]
Gotcha, that sounds great. Let me know when you all have reached that point, I'll be around! In the meantime, good luck with that redesign.
