### ISSUE TITLE
Read a synthetic individual file

### ISSUE THREAD

**Issue by SoccerGeekPhD** [InstituteforDiseaseModeling/covasim#235]
I would like to be able to have an synthetic, or real, data file of individuals to use more precise school, household and work data.  This could decouple synthetic population building from the execution of the simulation.

The file layout could be the RTI SynthPop one available for the US at https://fred.publichealth.pitt.edu/syn_pops.

The real data could be employees or First Responders added into a synthetic population.  This could enable separate counting of those special populations.

FWIW, I could not locate the import packages synthpops on PyPI to determine if synthpops enables this feature.

**Comment by lgeorge-idm** [comment]
@SoccerGeekPhD, we are working on releasing SynthPops which should address some (if not all) of this request.
