### ISSUE TITLE
contact matrices

### ISSUE THREAD

**Issue by dkhaz** [InstituteforDiseaseModeling/covasim#242]
Hello:

    I was trying to get the contact matrices that you plot in figure 4. In the data folder, I could not get that tables. Is it possible to get the tables ? Also, from the plots the contact matrices seem largely symmetrical. Shouldn't it be completely symmetrical ? 

Thanks and Regards,
Dhiraj

**Comment by cliffckerr** [comment]
Hi @dkhaz -- if you have a question about the paper, please reach out to us at covasim@idmod.org. Thanks!
