### ISSUE TITLE
Split dependencies into extras

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#243]
When running covasim in an HPC context, running from source is not an option. Being able to install only the necessary dependencies (i.e., excluding all of the webapp and development dependencies) to run covasim.

As a side note, some of the dependencies for `scirisweb` should also be investigated (e.g., `gitpython`, `memory-profiler`, etc.) as only required for development and not for using scirisweb more generally.

**Comment by lgeorge-idm** [comment]
This is to meet the request by Guillaume to be able to run covasim in a headless, clustered environment.

**Comment by ckerr-IDM** [comment]
The `python setup.py develop nowebapp` option should meet this requirement. This sounds like an OS/environment issue, not a Covasim issue.

**Comment by lgeorge-idm** [comment]
I agree. While simplifying the dependency graph is a good long-term goal, in that it's less actual bits being downloaded and (potentially) compiled, it doesn't solve the fundamental issue. Realistically, getting singularity working in the cluster is the actual solution and this is one piece of a stop-gap measure.
@devclinton any thoughts on how we could do this independently of the covasim project that doesn't inflict pain on both parties? Forking covasim temporarily?

**Comment by cliffckerr** [comment]
@lgeorge-idm @devclinton Closing for now as this isn't a Covasim issue.
