### ISSUE TITLE
Question on Contributing Guidelines

### ISSUE THREAD

**Issue by kjamessoda** [InstituteforDiseaseModeling/covasim#247]
Hi Everyone,

I have been tasked with modelling potential COVID dynamics in my university's residence halls so that we can design effective public health measures. I have been using Covasim for this task, but I added  a few features in my fork so that the contact networks would better correspond to the structure of a residence hall. I hope this is okay; the Disclaimer section said it was. 

However, I was uncertain after reading the contributor guidelines on whether I needed to report that I was making modifications in my fork if I am fine creating and testing any new features on my own; I decided to report it here just in case. I apologize if this was unnecessary. Let me know if you want further details. Thanks for all your hard work with this model! It has really made my life easier.

**Comment by ckerr-IDM** [comment]
This is totally fine, but thanks for letting us know! Drop us a line if we can be of help. There are a couple other people using it for similar purposes, and we'd be happy to put you in touch if you want.

**Comment by kjamessoda** [comment]
Sure, if it's not too much trouble, I would love to be put in contact with other folks doing similar things.

Thanks so much!

**Comment by cliffckerr** [comment]
@kjamessoda They're interested, so please send us an email (covasim@idmod.org) and we'll put you in touch. Thanks!

**Comment by cliffckerr** [comment]
Resolved
