### ISSUE TITLE
Missing parameter call in MultiSim plot() method

### ISSUE THREAD

**Issue by bu-bgregor** [InstituteforDiseaseModeling/covasim#248]
In the MultiSim plot() method (in run.py) when called to make a single line plot the show_args argument is not passed to the Sim plot() method.  

To reproduce: run some simulations with interventions using MultiSim.  The vertical dashed lines will be plotted at each intervention even when show_args turns them off:

```
sim = cv.Sim(interventions=....)
msim = cv.MultiSim(sim)
msim.reduce()
msim.plot(show_args={'interventions':False}) 
```

To fix, in the first lines of code in the MultiSim plot() method just add the show_args keyword to the call to the Sim plot() method:
```
if not plot_sims and self.which in ['combined', 'reduced']:
   fig = self.base_sim.plot(to_plot=to_plot, colors=colors, show_args=show_args, **kwargs)
```

**Comment by cliffckerr** [comment]
Thanks @bu-bgregor ! We're working on a bugfix release currently which should be merged in the next week or so.

**Comment by cliffckerr** [comment]
Fixed
