### ISSUE TITLE
[CI] Uncomment /tests/unittests

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#25]
Currently we don't run these because of how strict they are with changes of simulation results. Because this is stochastic models there is a lot of uncertainty about how it actually look like at the end (within reason).

We should refactor unittests in a way that they will always succeed unless someone makes meaningful change to results (one example would be, if mortality is 0, number of deaths should always be 0).

After that is done, we should uncomment these tests for CI

**Comment by ckerr-IDM** [comment]
Fixed by various PRs
