### ISSUE TITLE
Fix Excel test

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#257]
The Excel generation test seems to have broken:

https://github.com/InstituteforDiseaseModeling/covasim/pull/254/checks?check_run_id=859087617

Mostly likely due to the latest Sciris update (0.17.0 -> 0.17.1), but I'm not sure why it's failing? There's a separate test here which is still passing:

https://github.com/InstituteforDiseaseModeling/covasim/blob/master/tests/test_sim.py#L84

and the minimal

```
import covasim as cv
sim = cv.Sim()
sim.run()
sim.to_excel('test.xlsx')
```

also still works, so it looks like the issue might be with the test.

**Comment by CWiswell-IDM** [comment]
Fixed here: https://github.com/InstituteforDiseaseModeling/covasim/commit/8f364f62cd78d25ceca3d222eea0f0acbb7218f3
