### ISSUE TITLE
Transmission Tree Requires Additional Installation

### ISSUE THREAD

**Issue by SBuxton-IDM** [InstituteforDiseaseModeling/covasim#259]
The "make_transtree()" function within the analysis.py file doesn't work without networkx installed.

    1. Install covasim in a new virtual environment (python 3.7+)
    2. Run a sim like this:

```import covasim as cv
sim = cv.Sim()
sim.run()
tt = sim.make_transtree(to_networkx=True)
```

Expected:
    1.  Sim completes successfully and creates a transmission tree

Currently:
    1.  sim.make_transtree(to_networkx=True) yields an error because networkx is not installed

Notes:
If networkx is too large to download initially then there should be documentation such as a prominent comment in the class description. Currently there is a brief reference to networkx in the class description at the end: "If NetworkX is installed (required for most methods), "graph" includes an NX representation of the transmission tree." But, this could be made more noticeable.

**Comment by cliffckerr** [comment]
This is intentional behavior, so closing for now
