### ISSUE TITLE
analysis.compute_windows() should recognize dates declared after simulation execution

### ISSUE THREAD

**Issue by SBuxton-IDM** [InstituteforDiseaseModeling/covasim#262]
_For model issues:_
```python
sim = cv.Sim()

sim.run()
age_analyzer2 = cv.age_histogram(sim=sim, days=['2020-03-01', '2020-04-01', '2020-04-30'])

age_analyzer2.compute_windows()
assert len(age_analyzer2.window_hists) == len(3), "Number of histograms should equal number of days"
```
Expected Behavior:
Windows are computed and assertion passes.

Actual Behavior:
> File "c:\users\sbuxton\onedrive - institute for disease modeling\desktop\correctcovidmodel\covasim\covasim\analysis.py", line 229, in compute_windows
    raise ValueError(errormsg)
ValueError: You must have at least two dates specified to compute a window

Context:
This example works correctly when the analyzer is passed into the sim upon initialization.

**Comment by cliffckerr** [comment]
@SBuxton-IDM Haha nice find! So actually, this is impossible, since the state of the sim is not stored for the age histogram to analyze. Easiest solution is to either just remove the `agehist = cv.age_histogram(sim=sim)` syntax, or else change
```
        if sim is not None: # Process a supplied simulation
            self.from_sim(sim)
```
to
```
        if sim is not None: # Process a supplied simulation
            if self.days is not None: raise Exception('If a simulation is being analyzed post-run, only the last day is available')
            self.from_sim(sim)
```
or similar

**Comment by cliffckerr** [comment]
Closed by https://github.com/amath-idm/covasim/pull/664
