### ISSUE TITLE
Sim should produce error message when invalid snapshot analyzer is attached

### ISSUE THREAD

**Issue by SBuxton-IDM** [InstituteforDiseaseModeling/covasim#263]
When initializing a sim with a snapshot analyzer, the snapshot analyzer can be invalid and the sim will still run without error.

_For model issues:_
```
import covasim as cv

sim = cv.Sim(analyzers=cv.snapshot('2020-05-01'), pop_size=200)
sim.run()

```

**Expected Behavior**

Expected a date parsing error such as the one output by the age_analyzer() when an invalid
date is used.

**Actual Behavior**
No error is produced until the user tries to access the data in the snapshot in
which case a 'KeyError' is produced.

**Additional context**

The simulation used in this example terminates at 4-30-2020.

**Comment by cliffckerr** [comment]
Thanks @SBuxton-IDM , happy for you to implement the checks in the `age_histogram` intervention in `snapshot`

**Comment by cliffckerr** [comment]
Closed by https://github.com/amath-idm/covasim/pull/664
