### ISSUE TITLE
Investigate potential for duplicate infections of same individual on a single step

### ISSUE THREAD

**Issue by athompson-IDM** [InstituteforDiseaseModeling/covasim#267]
In this section, if p1 and p2 are not disjoint, it could have the same individual conceivably getting infected twice on a single step. 

1) Investigate: can it happen that p1 and p2 are not disjoint?
2) If so, how much does this matter, what are the implications in terms of correctness of simulating the duplicate infection on that step?

https://github.com/InstituteforDiseaseModeling/covasim/blob/9632dd27e892e55557e8f4a702e60a8642c3378b/covasim/sim.py#L503-505

**Comment by cliffckerr** [comment]
Closing this because it _could_ happen, but doesn't affect results. For example, one person in a household might get infected by two different people in the same household on the same day. But an infection is an infection with covid, so it doesn't matter.
