### ISSUE TITLE
Question about structure in "hybrid"

### ISSUE THREAD

**Issue by msosnovskaya** [InstituteforDiseaseModeling/covasim#268]
I am new in COVASIM and can't understand the structure in  "hybrid" population. How are agents connected? Is it a graph?

**Comment by cliffckerr** [comment]
Hi @msosnovskaya -- yes, you can think of it as a graph. If you're familiar with the NetworkX Python library, here is an example which plots the graph for the 'household' and 'school' contact networks for the hybrid population:
```
'''
Demonstrate visualization of the population contact structure using NetworkX
'''

import numpy as np
import networkx as nx
import covasim as cv

G = nx.Graph()

# Settings
pop_size = 100
pop_type = 'hybrid'
layers   = ['h', 's'] # Choose contact layer: can be one or more of 'h' (households), 's' (schools), 'w' (work), or 'c' (community)

# Create the simulation and population (we don't need to run it)
sim = cv.Sim(pop_size=pop_size, pop_type=pop_type) # Create sim
sim.initialize() # Initialize population

# Add nodes
for node in np.arange(pop_size):
    G.add_node(node)

# Add edges
for layer in layers:
    contacts = sim.people.contacts[layer] # e.g., pull out only household contacts
    for p1,p2 in zip(contacts['p1'], contacts['p2']): # Iterate over the contacts
        G.add_edge(p1, p2)

# Plot
nx.draw_shell(G)
```
This will give an output like the following:
![image](https://user-images.githubusercontent.com/3239256/90475444-4c8da680-e0dc-11ea-81f5-050be3c96cb0.png)
Household connections are between adjacent nodes on the edge of the graph, and school connections are shown between non-adjacent nodes.

**Comment by msosnovskaya** [comment]
Thanks for answering a lot! I couldn't find  the usage of Networkx in hubrid populations, only in SynthPop, that's why I'm asking/

**Comment by cliffckerr** [comment]
Resolved
