### ISSUE TITLE
[CI] Compare each run against baseline

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#27]
After #26 is done, we can add CI job that will compare results. It can generate it's own plot and show both of them next to each other and show difference in totals

**Comment by cliffckerr** [comment]
See #26

**Comment by jules2689** [comment]
#26 is done, however I dont think this specific issue is possible.

As our PRs come from forks, we lack the ability to comment on PRs. The best we could do is generate artifacts in CI that would be a bit of a pain to load.

**Comment by ckerr-IDM** [comment]
ah yeah we don't need this, will close now
