### ISSUE TITLE
question about hybrid school contacts

### ISSUE THREAD

**Issue by msosnovskaya** [InstituteforDiseaseModeling/covasim#270]
Hello! Could you tell, does hybrid population take into account children's age while making school contacts? I mean, do children aged 5 (for example) contact with children with the same age, or they can contact with children aged 1, 10, 20?

**Comment by cliffckerr** [comment]
Hi @msosnovskaya -- with hybrid, children of all ages mix (see https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/population.py#L301). For more precise modeling of school networks, you can use SynthPops:
https://github.com/InstituteforDiseaseModeling/synthpops
Currently this only includes data from Seattle, but we are working on supporting more locations.

**Comment by msosnovskaya** [comment]
thanks!
