### ISSUE TITLE
Simulation does not account for Asymptomatic/Pre-symptomatic Spread

### ISSUE THREAD

**Issue by bguan** [InstituteforDiseaseModeling/covasim#285]
**Is your feature request related to a problem? Please describe.**

Yes, without this feature the projection should not be used.  To be effective as a tool for planning school reopening, this simulation should account for asymptomatic/pre-symptomatic spread that has been shown in newer studies to be non-negligible. Recent [JAMA study](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2769235) shows ⅓ of subjects tested positive shows no symptom, ⅕ eventually show symptoms when in isolation. Conclusion from paper:

“Many individuals with SARS-CoV-2 infection remained asymptomatic for a prolonged period, and viral load was similar to that in symptomatic patients; therefore, isolation of infected persons should be performed regardless of symptoms.”

**Describe the solution you'd like**

Just like it allows for distancing effectiveness as a parameter to drive the simulation, it should allow an input for non-symptomatic contagious carrier as ratio of population, and percentage of test coverage for this group, and show the effect in the projection.

**Describe alternatives you've considered**

None.

**Additional context**

* JAMA,  ⅓ of subjects tested positive shows no symptom but some are contagious (https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2769235)

**Comment by cliffckerr** [comment]
This is already included in Covasim, see the `symp_prob` parameter. In Fig. 2 of this paper, we see 31% asymptomatic transmission:
https://www.medrxiv.org/content/10.1101/2020.07.15.20154765v3.full.pdf
![image](https://user-images.githubusercontent.com/3239256/93925166-99abfc00-fcca-11ea-9f88-7ae1255047ee.png)
