### ISSUE TITLE
MultiSim.compare() should make the resulting fig available?

### ISSUE THREAD

**Issue by rbelew** [InstituteforDiseaseModeling/covasim#288]
**Describe the bug**

`MultiSim.compare(do_plot=True)` builds but doesn't save or return the resulting plot

**To reproduce**

```python
import covasim as cv
sim = create_sim(bestPars,pars)
msim = cv.MultiSim(sim, n_runs=nruns)
msim.run() 
msim.compare(do_plot=True)
```

**Expected behavior**

i first expected  that the plot could be created with `do_save=True,fig_path="FIG.png"` parameters, but that generates exceptions:

		Traceback (most recent call last):
		File "/System/Volumes/Data/rikData/virtualenv/cvsim2/src/util.py", line 1299, in <module>
		reruns('Austria',dataDir,dbfile,nruns=8)
		File "/System/Volumes/Data/rikData/virtualenv/cvsim2/src/util.py", line 1278, in reruns
		compFig = msim.compare(do_plot=True,do_save=True,fig_path=plotDir +f'{country}-compare.png')
		File "/System/Volumes/Data/rikData/git/covasim-master-v-1-7-2/covasim/run.py", line 305, in compare
		fig = self.plot_compare(**kwargs)
		File "/System/Volumes/Data/rikData/git/covasim-master-v-1-7-2/covasim/run.py", line 472, in plot_compare
		return cvplt.plot_compare(df, log_scale=log_scale, **kwargs)
		TypeError: plot_compare() got an unexpected keyword argument 'do_save'

Digging around, i find specifying `do_plot=True` to `MultiSim.compare()` does produce a plot via `MultiSim.plot_compare()` --> `cvplt.plot_compare()`, but it never makes it out.

my current hack modifies end of `MultiSim.compare()` to return EITHER  the dataframe OR the fig; this is an unfortunate forced choice:)

        if do_plot:
            fig = self.plot_compare(**kwargs)
        else:
            fig = None

        df = pd.DataFrame.from_dict(resdict).astype(object) # astype is necessary to prevent type coercion
        if output:
            return df
        else:
            print(df)
            return fig

**Platform (please complete the following information):**
 
 - Covasim version: Covasim 1.7.2 (2020-09-24)
 - OS: [e.g. Linux, Android] OSX 10.15

**Additional context**

**Comment by cliffckerr** [comment]
Thanks @rbelew . Covasim doesn't always follow the Python dictum of "There should be one, _and preferably only one_, way of doing things". So here I would suggest instead doing :
```
import covasim as cv
sim = create_sim(bestPars,pars)
msim = cv.MultiSim(sim, n_runs=nruns)
msim.run() 
df = msim.compare()
fig= msim.plot_compare() # nb, may not actually return the figure currently!
```
```

**Comment by cliffckerr** [comment]
Agree perhaps not ideal behavior, but closing for now
