### ISSUE TITLE
Make image smaller

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#29]
Currently our image is multi-GB in size. Waaay to much for this project.

**Comment by inc0** [comment]
We could use miniconda or just `python:3` base image and install everything with pip

**Comment by adityasharad** [comment]
Happy to take this as suggested. I'll base my changes on https://github.com/InstituteforDiseaseModeling/covasim/pull/32/ to avoid conflicts.

miniconda looks it results in a smaller image (3.35 -> 1.96GB), but with more changes needed to pick up `gcc` and install dependencies, while `python:3` is less of a size win (3.35 -> 2.11GB) but keeps the install script mostly similar.
