### ISSUE TITLE
Possible type issue

### ISSUE THREAD

**Issue by sba5827** [InstituteforDiseaseModeling/covasim#291]
https://github.com/InstituteforDiseaseModeling/covasim/blob/a55a849b2a1666e866c552356020a85fe7bd521f/covasim/base.py#L1235-L1238

cvu.find_contacts expects an int64 array, but the if statement does not ensure that the datatype is correct

**Comment by cliffckerr** [comment]
Thanks @sba5827 -- in our 2.0.0 release slated for next week, this issue will be fixed.

**Comment by cliffckerr** [comment]
Fixed in version 2.0 (now released)
