### ISSUE TITLE
Overriding quar_period to None for contact tracing

### ISSUE THREAD

**Issue by mccraebears** [InstituteforDiseaseModeling/covasim#292]
On line 876 of `covasim/interventions.py`, the initialization sets `self.quar_period = None`. However, `quar_period` is an optional input argument, which defaults to `None`. Should it instead be `self.quar_period = quar_period`?

https://github.com/InstituteforDiseaseModeling/covasim/blob/a55a849b2a1666e866c552356020a85fe7bd521f/covasim/interventions.py#L876

**Comment by cliffckerr** [comment]
Thank you @mccraebears  -- confirming that this is a bug, which will be fixed in our 2.0.0 release slated for release next week.

**Comment by cliffckerr** [comment]
Fixed in version 2.0 (now released)
