### ISSUE TITLE
Most desired way to load custom population

### ISSUE THREAD

**Issue by rlatkows** [InstituteforDiseaseModeling/covasim#294]
I would like to load my own custom population with several layers of connections.
What would be the suggested way to do it?

**Comment by cliffckerr** [comment]
Hi @rlatkows , there are a few options here. You can take a look at [population.py](https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/population.py) and see how the population is constructed. For a more sophisticated solution, you can look at [SynthPops](https://docs.idmod.org/projects/synthpops/en/latest/), which is a very flexible package for generating synthetic populations. If you'd like to discuss this in more detail, please feel free to reach out to us at covasim@idmod.org.

**Comment by rlatkows** [comment]
Done by extending inherited classes with custom make_pop methods.
