### ISSUE TITLE
Add additional export options

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#299]
Expand on https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/base.py#L530
- [ ] `sim.to_df()`
- [ ] `sim.to_hdf5()`

Also look at `https://github.com/sciris/sciris/blob/develop/sciris/sc_fileio.py#L509` and consider adding
- [ ] `sc.loadhdf5()`
- [ ] `sc.savehdf5()`
(although not needed if pandas does basically the same thing as it probably does!)

**Comment by wwaites** [comment]
This looks reasonable. Simplest would just be the `to_df` version I think because then you can use whichever method you like to save it (e.g. there are choices for how you put data into an HDF5 file, pandas has its way, sciris probably has its way, probably best not to get in the middle of that)

**Comment by cliffckerr** [comment]
Going to close since anyone who wants hdf5 probably knows how to do it with pandas, and it's not clear what additional functionality would be added by having a wrapper beyond what should already be a one-liner: e.g. `pd.DataFrame(sim.to_json()).to_hdf5()`.

**Comment by cliffckerr** [comment]
Actually, I forgot that this included just `to_df()` too ;) Might be worthwhile, will reopen.

**Comment by cliffckerr** [comment]
Closed in 3.0.2
