### ISSUE TITLE
Include healthsystems into web

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#3]
Currently, there are no configurations in webapp to address eventual shortages of, for example, ICU beds. It would be great to include these into webapp. This will mean that when severe cases pass pre-configured threshold, mortality increases.

**Comment by sayers24** [comment]
Would you be able to give pointers on where the backend code is accepting this parameter so we know what key/value type to pass?

**Comment by ckerr-IDM** [comment]
Sufficient for now, will reopen if more detailed needs arise
