### ISSUE TITLE
Clean up controller with form model

### ISSUE THREAD

**Issue by gwincr11** [InstituteforDiseaseModeling/covasim#30]
Currently the logic for the `run_sim` endpoint is quite large. Lets move the params validation and cleaning into a form model. 
https://github.com/InstituteforDiseaseModeling/covasim/blob/cfc73005f97acbefbf62437b30503aef36621abc/covasim/webapp/cova_app.py#L126-L175

We can also add unit testing for the form model once it is created.

**Comment by gwincr11** [comment]
We prefer server side validation so we are not open to ddos attacks requesting huge calculations from non-browser clients.

**Comment by cliffckerr** [comment]
Seems to be working for now
