### ISSUE TITLE
Probabilities- 1.0 infection, symptomatic, severity, critical, death probabilities should not have recoveries

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#31]
Found in regressing test cases.

In this simulation, every agent starts as infected, and the probabilities should put all of them in the fatal bucket:
>
        "n": 500,
        "n_infected": 500,
        "rel_crit_prob": 1.0,
        "rel_death_prob": 1.0,
        "rel_severe_prob": 1.0,
        "rel_symp_prob": 1.0,

The durations for each of those phases should be a constant 0 (a couple of examples)
>            "crit2die": {
                "dist": "normal",
                "par1": 1,
                "par2": 0
            },
>             "exp2inf": {
                "dist": "normal",
                "par1": 0,
                "par2": 0
            },

(I think I got all of them) but when the simulation runs, we only see 6 deaths and 494 recoveries.

Steps to repro:
Convert the attached TEST_sim_from_results_json.txt to a .py file
copy that .py file and the attached txt file into a directory where covasim is installed
Run the script and look at the console output

EXPECTED: 500 agents, 500 deaths
CURRENTLY: 500 agents, 6 deaths, 494 recoveries
[TEST_sim_from_results_json.txt](https://github.com/InstituteforDiseaseModeling/covasim/files/4424284/TEST_sim_from_results_json.txt)

[DEBUG_test_disease_progression.DiseaseProgressionTests.txt](https://github.com/InstituteforDiseaseModeling/covasim/files/4424255/DEBUG_test_disease_progression.DiseaseProgressionTests.txt)

**Comment by cliffckerr** [comment]
@CWiswell-IDM This is expected behavior, these probabilities now multiply the actual probabilities in `set_progression`. See `webapp/cova_app.py` for an example translating these into absolute rates. We moved away from using absolute rates since was too complicated with age-dependent mortality.

**Comment by CWiswell-IDM** [comment]
Cannot find a set_progression method anywhere. Are you referring to parameters.get_default_prognoses?

**Comment by CWiswell-IDM** [comment]
Ah, people.set_prognoses
