### ISSUE TITLE
Add the possibility to explicitly set the number of vaccinations

### ISSUE THREAD

**Issue by imcatta** [InstituteforDiseaseModeling/covasim#311]
**Is your feature request related to a problem? Please describe.**

Most countries make available data on the number of vaccinations carried out. Currently, it's hard to calibrate Covasim using those data, because the `vaccinate()` intervention works based on the `prob` parameter.

**Describe the solution you'd like**

It would be very useful to add the ability to explicitly set the number of vaccinations per day, similarly to the `test_num()` intervention. In addition, it would be important to retain the ability to target a specific subpopulation.

**Describe alternatives you've considered**

Use the `subtarget` parameter to explicilty target people, but it's hard to make it work if dynamic rescaling is on.

**Additional context**

An example of vaccinations data available [https://github.com/italia/covid19-opendata-vaccini](https://github.com/italia/covid19-opendata-vaccini).

**Comment by cliffckerr** [comment]
Thanks @imcatta ! We are aware of this and it didn't quite make it into the 3.0.2 release, but we're hoping it'll make it into the 3.0.3 release :)

**Comment by imcatta** [comment]
Any updates? :)

**Comment by cliffckerr** [comment]
@imcatta Sorry, it took a while! But this was part of the Covasim 3.0.6 release last week, a new intervention called `cv.vaccinate_num()`:
https://docs.idmod.org/projects/covasim/en/latest/whatsnew.html#version-3-0-6-2021-06-21
