### ISSUE TITLE
Add a contributing doc

### ISSUE THREAD

**Issue by gwincr11** [InstituteforDiseaseModeling/covasim#36]
There are beginning to be a lot of scattered readme's I propose we put together a doc focused on getting contributors up and running. It should include at least the following

- [x] Welcome to the project.
- [x] Links to important documents
    - [x] Issues
    - [x] Docs
    - [ ] Maybe a glossary of terms
- [x] Overview of types of contributions we are looking for.
- [x] Communicating in GitHub
- [x] Setup
    - [x] Docker
    - [x] Non-docker
- [x] Running tests
- [x] Reporting bugs
- [x] How to submit a pr
- [x] Making a feature request
- [ ] Where can I get help?
- [x] Code of conduct

Some examples:
https://github.com/integrations/slack/blob/master/CONTRIBUTING.md
https://github.com/integrations/slack/blob/master/CODE_OF_CONDUCT.md

GitHub has some starter template as well: 
https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

We may also want to create some templates to encourage proper formating.
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by cliffckerr** [comment]
Closed by #140
