### ISSUE TITLE
Is it possible to eliminate all non-determinism apart from generating the age of each agent?

### ISSUE THREAD

**Issue by AndrewC19** [InstituteforDiseaseModeling/covasim#368]
Hi,

I am trying to run covasim lots of times to observe the effect of changing the age distribution on cumulative infections.

I would like to set the age distribution and then run the model 30 times to get 30 different runs with different samples from the same age distribution. 

Since I want to isolate the effect of age, I need to block other sources of non-determinism by setting a fixed random seed. However, this means that each of the 30 runs yields the same sample 30 times.

I would like to be able to hold everything constant apart from the process of sampling the age of each agent in the population. Is there a simple way for me to achieve this?

Thanks!

**Comment by cliffckerr** [comment]
Closing since resolved
