### ISSUE TITLE
Project management tooling

### ISSUE THREAD

**Issue by gwincr11** [InstituteforDiseaseModeling/covasim#37]
We are starting to get more people involved in this project. It maybe nice to allow some people in the org do some simple project management to make it easier to tell what is open to be worked on and what is in progress.

Proposal:
- [ ] Setup a simple project board with the backlog, in progress and finished columns. Setup automation on this board to automatically update when possible.
- [ ] Allow some of the core contributors to self assign issues.
- [ ] Determine who is in charge of reviewing and merging code.
- [ ] Define a process for requesting reviews and reviewing/merging items.

**Comment by inc0** [comment]
I'm able to do all these things so I'll just work on that

**Comment by gwincr11** [comment]
We also discussed adding a codeowners file and a few separate teams. Those in charge of scientific reviews, maybe a devops group and a webapp group?

**Comment by cliffckerr** [comment]
Sounds good. @inc0 and I will be the main reviewers for the time being.

**Comment by cliffckerr** [comment]
With the board (thanks @lgeorge-idm !), I'm going to call this done :)
