### ISSUE TITLE
Possible typo in Voila doc example on ipywidgets import

### ISSUE THREAD

**Issue by edwenger** [InstituteforDiseaseModeling/covasim#374]
Really minor thing I came across trying to build upon the Voila example code from the docs:
https://github.com/InstituteforDiseaseModeling/covasim/blob/9e94ccda7616fba4faf9b010f8cb3952fff7f051/docs/tutorials/tut_deployment.ipynb#L81

I get an error that ipywidgetsets can't be imported, but if I switch that to just ipywidgets, it works fine.

Not sure if that's a system environment difference or a typo, but thought I'd flag in case you know.

Thanks.

**Comment by cliffckerr** [comment]
Thanks @edwenger ! Agree this looks like a typo.

**Comment by cliffckerr** [comment]
Fixed
