### ISSUE TITLE
Add front end tooling

### ISSUE THREAD

**Issue by gwincr11** [InstituteforDiseaseModeling/covasim#38]
Currently we have a very simple front end with a single js file and a single css file. Do we want to add some level of testing, package management and build tooling?

**Comment by jules2689** [comment]
I would think that the front end will stay fairly simple using the single JS file as is. If we get more complicated, then I think we would want to add some package management and stuff. I could help with that.

**Comment by gwincr11** [comment]
I think we may benefit from at least some level of testing. The web app is pretty un-tested in general, and there will likely be a lot of growth in complexity at the ui level. This will give us a level of confidence as things grow and put us in a better place to add complexity later.

It will also encourage modularization instead of just dumping everything into a large file, there is all ready a fair bit of duplication in the code that could benefit from being dried up. I am looking at you data model and html partials.

**Comment by deviozc** [comment]
I think some level of dependency management on JS would be nice. It is not so clear what library is available to use.

**Comment by cliffckerr** [comment]
Let's revisit this if the webapp expands to the point where this is required.
