### ISSUE TITLE
Hanging comma on `plots` value in defaults.get_default_plots() causes `sim.plot(to_plot='seir')` to fail

### ISSUE THREAD

**Issue by rbelew** [InstituteforDiseaseModeling/covasim#383]
**Describe the bug**

[Hanging comma here](https://github.com/InstituteforDiseaseModeling/covasim/blob/bcb1d26f3fdf8e57e77db2349e6ee9904547a0d7/covasim/defaults.py#L434)

makes `plots` become a **tuple**, and `plotting.handle_to_plot()` gets confused

**To reproduce**

_For model issues:_
```python
import covasim as cv
sim = cv.Sim(pars={}) # Configure the simulation
sim.run() # Steps required to produce the behavior

sim.plot(to_plot='seir')
```

**Expected behavior**

**Screenshots or outputs**

Produces graph attached with comma removed

**Platform (please complete the following information):**
 - Covasim version: 3.1.2
 - OS: OSX 10.15.7

**Additional context**
![ARG_2-seir](https://user-images.githubusercontent.com/120920/161399539-00c84c9e-5cfa-4f19-a3a8-184990984316.png)

**Comment by cliffckerr** [comment]
Fixed -- thanks @rbelew !
