### ISSUE TITLE
Release log date bug

### ISSUE THREAD

**Issue by xmusphlkg** [InstituteforDiseaseModeling/covasim#386]
**Describe the bug**

The date seems to be wrong. Version 3.1.2 was released in 2022, and the label was 2021-01-16.

**To reproduce**

https://github.com/InstituteforDiseaseModeling/covasim/blob/master/CHANGELOG.rst#version-312-2021-01-16

**Comment by cliffckerr** [comment]
Thanks @xmusphlkg , well spotted! This has been fixed.
