### ISSUE TITLE
Covasim tutorials on Binder fail on sciris import

### ISSUE THREAD

**Issue by edwenger** [InstituteforDiseaseModeling/covasim#389]
Binder-hosted covasim tutorials fails on sciris import (specifically some deprecated matplotlib.colors function calls from sc_colors.py)

<img width="1105" alt="Screen Shot 2022-10-28 at 14 00 51" src="https://user-images.githubusercontent.com/9509374/198735166-3a25433d-8f2f-40fc-bc6a-8cfb919df08b.png">

Looks as if pip install sciris==2.0.3 (instead of 2.02, which the tutorial loads by default) is the fix.
https://github.com/sciris/sciris/blame/develop/sciris/sc_colors.py

**Comment by cliffckerr** [comment]
Thanks @edwenger , will get this fixed today!

**Comment by cliffckerr** [comment]
Fixed -- bumping the version in `requirements.txt` seemed to trigger a cache clear for Binder.
