### ISSUE TITLE
TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by benisonp** [InstituteforDiseaseModeling/covasim#4]
Followed the instructions, but got the error in the title when trying to import covasim. Same error if I install in terminal and try to run a sim. 

Thanks!

**Comment by ckerr-IDM** [comment]
@benisonp Could you explain what you did and what the error message is? Are you sure you're using Python 3 and not Python 2?

**Comment by benisonp** [comment]
@ckerr-IDM pip install, then tried 'import covasim as cv', which returned the following error message: TypeError: attrs() got an unexpected keyword argument 'eq'

I then tried 'python setup.py develop' in terminal followed by 'python examples/simple.py', but that returned the same error message. 



And yes 100% sure on Python3.

**Comment by ckerr-IDM** [comment]
@benisonp Can you please include the full stack trace?

**Comment by benisonp** [comment]
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a13c33294d9c> in <module>
----> 1 import covasim as cv

~/Documents/Data Science/covasim/covasim/__init__.py in <module>
      4 
      5 #%% Check that requirements are met
----> 6 from . import requirements
      7 
      8 #%% Import the actual model

~/Documents/Data Science/covasim/covasim/requirements.py in <module>
     91 # Perform the version checks on import
     92 check_sciris()
---> 93 check_scirisweb(die=False)
     94 check_extra_libs()

~/Documents/Data Science/covasim/covasim/requirements.py in check_scirisweb(die)
     39     # Try imports
     40     try:
---> 41         import scirisweb
     42     except ModuleNotFoundError:
     43         import_error = 'Scirisweb not found; please rerun setup.py or install via "pip install scirisweb"'

~/anaconda3/lib/python3.7/site-packages/scirisweb-0.16.6-py3.7.egg/scirisweb/__init__.py in <module>
     15 from .sw_tasks     import * # analysis:ignore
     16 from .sw_datastore import * # analysis:ignore
---> 17 from .sw_app       import * # analysis:ignore
     18 from .sw_server    import * # analysis:ignore
     19 

~/anaconda3/lib/python3.7/site-packages/scirisweb-0.16.6-py3.7.egg/scirisweb/sw_app.py in <module>
     17 from flask import Flask, request, abort, json, jsonify as flask_jsonify, send_from_directory, make_response, current_app as flaskapp, send_file
     18 from flask_login import LoginManager, current_user
---> 19 from twisted.internet import reactor
     20 from twisted.internet.endpoints import serverFromString
     21 from twisted.logger import globalLogBeginner, FileLogObserver, formatEvent

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/reactor.py in <module>
     36 import sys
     37 del sys.modules['twisted.internet.reactor']
---> 38 from twisted.internet import default
     39 default.install()

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/default.py in <module>
     54 
     55 
---> 56 install = _getInstallFunction(platform)

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/default.py in _getInstallFunction(platform)
     48             from twisted.internet.pollreactor import install
     49         else:
---> 50             from twisted.internet.selectreactor import install
     51     except ImportError:
     52         from twisted.internet.selectreactor import install

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/selectreactor.py in <module>
     16 
     17 from twisted.internet.interfaces import IReactorFDSet
---> 18 from twisted.internet import posixbase
     19 from twisted.python import log
     20 from twisted.python.runtime import platformType

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/posixbase.py in <module>
     16 from zope.interface import implementer, classImplements
     17 
---> 18 from twisted.internet import error, udp, tcp
     19 from twisted.internet.base import ReactorBase, _SignalReactorMixin
     20 from twisted.internet.main import CONNECTION_DONE, CONNECTION_LOST

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/udp.py in <module>
     51 
     52 # Twisted Imports
---> 53 from twisted.internet import base, defer, address
     54 from twisted.python import log, failure
     55 from twisted.python._oldstyle import _oldStyle

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/base.py in <module>
     25 
     26 from twisted.internet import fdesc, main, error, abstract, defer, threads
---> 27 from twisted.internet._resolver import (
     28     GAIResolver as _GAIResolver,
     29     ComplexResolverSimplifier as _ComplexResolverSimplifier,

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/_resolver.py in <module>
     23 from twisted.internet.defer import Deferred
     24 from twisted.internet.threads import deferToThreadPool
---> 25 from twisted.internet.address import IPv4Address, IPv6Address
     26 from twisted.python.compat import nativeString
     27 from twisted.internet._idna import _idnaBytes

~/anaconda3/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-macosx-10.7-x86_64.egg/twisted/internet/address.py in <module>
     99 
    100 
--> 101 @attr.s(hash=False, repr=False, eq=False)
    102 @implementer(IAddress)
    103 class UNIXAddress(object):

TypeError: attrs() got an unexpected keyword argument 'eq'

**Comment by benisonp** [comment]
Thanks for the patience, apologies for the lack of clarity.

**Comment by ckerr-IDM** [comment]
It seems to be a Twisted error -- I suggest trying to install that separately. If that doesn't work, use `python setup.py develop nowebapp` to skip Twisted installation.

**Comment by benisonp** [comment]
@ckerr-IDM That works! Thanks so much!
