### ISSUE TITLE
The footer.html customization isn't being applied in the Sphinx PyData theme

### ISSUE THREAD

**Issue by JSchripsema-IDM** [InstituteforDiseaseModeling/covasim#423]
**Describe the bug**

There's extra information about the license, privacy notice, and terms of use that isn't being applied to the compiled HTML in the PyData theme. It appears others have hit this issue and identified a fix here: https://github.com/pydata/pydata-sphinx-theme/issues/1284
<img width="947" alt="covasimfooter" src="https://github.com/InstituteforDiseaseModeling/covasim/assets/20909236/b4e72b10-8d5d-4099-8067-52514b66fa80">

**Comment by cliffckerr** [comment]
Fixed
