### ISSUE TITLE
Scrape best available demographics data

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#44]
Currently, Covasim with the `usepopdata = False` option uses a hard-coded age distribution from the US:
https://github.com/institutefordiseasemodeling/covasim/blob/develop/covasim/people.py#L315

We need to make this adaptable to as many different locations as possible. The best source for data o this is the UN World Pop:

https://population.un.org/wpp/

We need a simple way of being able to choose the population data (i.e., set the `age_data` variable) based on any country in the world, e.g. `make_randpop(sim, location='ethiopia')`.

**Comment by inc0** [comment]
For US - we have 
https://censusreporter.org/
https://gii.dhs.gov/hifld/content/hifld-data-catalog - I'm exploring this for country-wide state demographics, schools etc

**Comment by inc0** [comment]
https://github.com/neherlab/covid19_scenarios/blob/da1381c429471c3d57b02cd5a7b6dc46e645c0b3/src/assets/data/country_age_distribution.json this is useful too

**Comment by lgeorge-idm** [comment]
@inc0, I'm pretty sure we have this data in house. @dennish737?

**Comment by cliffckerr** [comment]
Have for countries, separate issue for US states
