### ISSUE TITLE
Enable make_randpop to accept country as parameter

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#45]
Right now https://github.com/institutefordiseasemodeling/covasim/blob/develop/covasim/people.py#L315 is hardcoded on Seattle. We could use https://github.com/neherlab/covid19_scenarios/blob/da1381c429471c3d57b02cd5a7b6dc46e645c0b3/src/assets/data/country_age_distribution.json to get per-country ratios. Later we can write our own scraper.

**Comment by gwincr11** [comment]
I will look into this.

**Comment by inc0** [comment]
We could use this with CLI too - `covasim --country USA --state Oregon`

**Comment by cliffckerr** [comment]
Fixed in one of the many PRs
