### ISSUE TITLE
Generate age distributions per state

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#47]
Use census data to generate age distributions per state, this will enable us to get integrated into unified UI quickly

**Comment by gwincr11** [comment]
Do we have census sources we want to use? Are we looking to target just the USA or other countries as well? Where does this integrate into the Sim?

**Comment by cliffckerr** [comment]
Grace Huynh from Microsoft suggested this source:
https://data.census.gov/cedsci/table?g=0100000US.050000&layer=VT_2018_050_00_PY_D1&tid=ACSST5Y2018.S0101&vintage=2018&hidePreview=false&t=Age%20and%20Sex%3APopulations%20and%20People

**Comment by gwincr11** [comment]
Would we want to pull that in and check it into the repo like we did with country population? What is the desired final format? Same as the country format?

**Comment by cliffckerr** [comment]
@gwincr11 yep i think it can be super simple -- just like
https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/data/country_age_distributions.py
except per state (i think that data is down to the county level, we don't need that, just by state). format doesn't have to match neher lab, can just add a separate loader to
https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/data/loaders.py
if 150 country age distribution is 40 kb then 50 states should be 15 kb so totally fine to commit directly to the repo

**Comment by cliffckerr** [comment]
(btw, reason to include as python files is so it plays nicely with pip and doesn't require MANIFEST.in gymnastics -- can rethink that approach if/when it becomes necessary to)

**Comment by cliffckerr** [comment]
Closed by @gwincr11 (#124 )
