### ISSUE TITLE
Write scheduled GH actions to pull country epi data

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#48]
For now best data we know of is available https://github.com/CSSEGISandData/COVID-19 here. We can pull time series data, process it and cache it locally with scheduled GitHub actions.

**Comment by gwincr11** [comment]
When you say cache it locally, do you actually mean check it in with a pull request?

**Comment by inc0** [comment]
Or directly commit into repo, at least for now, via deploy key. @cliffckerr are you ok with this approach?

Every day (or hour) we could pull latest data from JHL, process it and cache it locally. We'd need to create [deploy key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) and save it as action secret

**Comment by cliffckerr** [comment]
@inc0 if we're committing data, this should probably not be in the covasim repo -- potentially synthpops but maybe best to have a separate module/repo for it?

**Comment by gwincr11** [comment]
I am working on a script to pull in the neherlab data as part of: https://github.com/InstituteforDiseaseModeling/covasim/issues/45

I ended up with a folder structure of:
`covasim/datasets/sources/` Where the data will live
`covasim/dataset/translators.py` Which is holding the translators to get datasets to the format we want
`covasim/datasets/update_sources.py` Which pull in the source files when run.

I was also thinking about adding a reference file that could tell us which of the source files contain which countries data. This could be generated by update sources and dropped in the sources file.

I was speaking with Scott Ayers and he could also use the reference file for some front end work he is doing. So it serves a few purposes.

**Comment by hamelsmu** [comment]
Some comments/questions

- The John Hopkins data is only updated daily, no need to pull more often
- Why do we need to check in a copy of the data into this repo?  We can reference the URL of the data directly.  Most data science libraries allow you to reference the URLs of CSV files as a filehandle

**Comment by ckerr-IDM** [comment]
@hamelsmu yes, i think we're in agreement -- we'd have a script to manually update the data into a git-ignored folder

**Comment by hamelsmu** [comment]
Ah yes, sorry I misread the thread -- my apologies
