### ISSUE TITLE
Automatic calibration

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#49]
Once #43 is done, we need to calibrate to the data. The `Sim` object already has a `likelihood()` method, but this needs to be improved (more data types, probably using cumulative rather than daily counts, etc.). We also need to decide what model parameters will be used for fitting -- potentially just `beta` and `n_infected`, but if others, may need a smarter optimization approach. We are almost there with a fancy method called BINNTS (bootstrapped iterative nearest-neighbor threshold sampling), but it's not quite ready to go, so could also look into an off-the-shelf method, especially if we just want the MLE and don't need the whole posterior.

**Comment by inc0** [comment]
@cliffckerr so my plan will be to setup infrastructure for Bayesian

**Comment by rnunez-IDM** [comment]
Based on our conversation a few minutes ago, here are a few items/additional considerations for this issue:
- We will leverage parameter sweeps with Weights & Biases (code for doing this is already in the repository)
- Probably add some likelihood-free methods when it becomes necessary
- Need to add a few calibration scenarios to complete this issue (it could be a synthetic scenario and 2 or 3 scenarios using publically available data for certain regions of interest)

**Comment by cliffckerr** [comment]
Even though this isn't done, will close this issue and open a new one since the goals have shifted.
