### ISSUE TITLE
Upper limit of 56,800,235 people in the simulation

### ISSUE THREAD

**Issue by vishal-wiai** [InstituteforDiseaseModeling/covasim#5]
When generating random population, it uses `sciris.uuid()` to generate unique IDs for the population. Due to `safety` attribute in`fast_uuid()` function in `sciris` it limits the simulation to run only for 56 million people. By default it should be able to generate 56,800,235,584 UIDs. 

This is the error
`ValueError: With a UID of type "ascii" and length 6, there are 56800235584 possible UIDs, and you requested 100000000, which exceeds the maximum allowed (56800235)`

**Comment by cliffckerr** [comment]
This is fixed, will make PR soon

**Comment by cliffckerr** [comment]
Closed by https://github.com/amath-idm/covasim/pull/239
