### ISSUE TITLE
Enable UI ground truth overlay

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#50]
Since we'll have latest data cached by #48 and countries selectable by #44, we can overlay number of confirmed cases, deaths and recoveries over simulation

**Comment by cliffckerr** [comment]
This is already in the BE, see `data_mapping` in `sim.py`. Not sure about the FE, but not 100% sure we want to stick with Plotly graphs anyway? The duplication is annoying, and if we're going to have custom frontend graphs, maybe better to use something more powerful like d3 (or what Brian has for the unified one).

**Comment by cliffckerr** [comment]
Closed by #79
