### ISSUE TITLE
Consider using logger instead of verbose

### ISSUE THREAD

**Issue by ckerr-IDM** [InstituteforDiseaseModeling/covasim#59]
Currently, stdout is managed by a `verbose` variable passed between functions. This works, but better options might be available. Consider replacing with logger for greater flexibility. 

Requirements:
* Equally easy to configure, e.g. replacing `sim.run(verbose=1)` with `sim.run(verbose='info')` is OK; `from covasim.utils import logger; logger.setLevel('INFO'); sim.run()` is not
* Same levels of detail are implemented: e.g. 0 = only warnings/errors to stdout, 1 = default output, 2 = print everything possible (debug).

@RomeshA do you want to take a look at this? cc @gwincr11

**Comment by cliffckerr** [comment]
Closing for now since verbose seems to work and loggers are kind of ugly :)
