### ISSUE TITLE
Enable full state runs with scaling

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#62]
Covasim can run pretty well with populations up to ~100k. This is statistically enough to model even multi-milion pops, assuming we can generate sample similar to overall population.

We can include functions that will automatically scale results and iterations to show numbers in real state population. So, create 100k pop, calculate fraction of actual pop (say, for 5M state, it's going to be 0.02) and multiply all numbers by it.

@Cliff one open question I'd have in this approach would be how to handle initial infections? Should we also scale them and round to ceiling? So for 10 initially infectious in 5M state, during sims we'll run 1? That will skew results quite drastically if I'm correct. Ideas?

**Comment by ckerr-IDM** [comment]
We won't want to start from a single infection -- too much stochasticity anyway. This question is a good one, related to this:
https://github.com/amath-idm/covasim/issues/23

**Comment by inc0** [comment]
Idea @cliffckerr had and I'll prototype:

When we reach certain threshold of infections (say, 50%, but configurable) we scale up frame of reference by 2 (or later, configurable).
That means:
1. De-infect random 50% of infected
2. Resurrect 50% of dead
3. Re-susceptible(?) 50% of recovered
4. Multiply every summary stat by 2

**Comment by cliffckerr** [comment]
@inc0 sounds good. the main change that needs to happen is to expand the definition of `scale` to have it be an array of length `n_days` rather than a scalar (or better, keep scale a scalar but introduce a `scalevec` parameter for this). but yeah basically just loop over 50% of all non-susceptibles and restore them to the susceptible state (no method for this currently, but should be added)

**Comment by dlchao** [comment]
Doesn't scaling affect elimination dynamics and the time to the epidemic peak? You can't just re-scale the y-axis on your plots. And now if you want to start with 500 cases in the real population of 5,000,000 but it is implemented as 1 case in an actual population of 10,000 people, then you will get tons of stochasticity when there shouldn't be with 500 initial cases.

**Comment by ckerr-IDM** [comment]
@dlchao it's a good point, we'll need to be able to scale down as well as up! but the idea is to get around exactly that -- we start with 500 cases in a population of 50k, and then when we get to 5000 cases we rescale to 500k, etc. -- so we never have fewer than 500 simulated cases but also never have more than 5000

**Comment by inc0** [comment]
Another thing is that we're rescaling by factor of 2 by default and scaling multiple times (every few days once epidemy picks up).

example: 10k internal population and 2M target population, start with 10 infections:
* keep going until you reach 5000 or less susceptibles
* cut make half of non-susceptibles susceptible again, multiply all numbers by 2
* reach 10000 (5000 * 2), multiply by 2 again
* repeat

**Comment by ckerr-IDM** [comment]
as i mentioned in my comment on the PR we definitely don't want to let prevalence reach 50% -- maybe not even 5% -- before rescaling

**Comment by inc0** [comment]
I've set it up to 5% and it's configurable, we can experiment with even lower thresholds if need be

**Comment by dlchao** [comment]
How do you make transmission trees when you have dynamic rescaling of the population?

**Comment by ckerr-IDM** [comment]
you wouldn't be able to use transmission trees with this -- assuming you probably wouldn't be doing a full transmission tree for >1m infections

**Comment by inc0** [comment]
Sorry, I'm still novice in epi simulation and learning nomenclature, what do you mean by transmission trees? We don't touch contact network underneath, so one school will represent 2 schools after rescaling.

**Comment by inc0** [comment]
Right, this is mainly to produce numbers per day for big populations, probably good to document when not to use dynamic resampling
