### ISSUE TITLE
Write export method for scenarios

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#64]
See `base.py:BaseSim` for `to_json()` and `to_excel()` methods. Need to add these to the Scenarios class (`run.py`).

**Comment by RasmusWL** [comment]
Seems like this was fixed by https://github.com/InstituteforDiseaseModeling/covasim/commit/953cde90430a7fb3b3ce9170ca83d0f2a31eef14 ? :blush:

**Comment by ckerr-IDM** [comment]
Ah yes, forgot to close the issue :)
