### ISSUE TITLE
Scrape workplace/industry data immediately

### ISSUE THREAD

**Issue by DMistry-IDM** [InstituteforDiseaseModeling/covasim#69]
Got a request to look at reopening workplaces, perhaps by industry type or size. So, I could use a pair of hands or more to look at https://www.bls.gov/oes/current/oes_42660.htm and grab data from there on workplaces. Specifically data on age of workers, types of industry, workplace sizes (by industry too if available), at the finest granularity you can find (this page points at the Seattle-Tacoma-Bellevue metro area). Simple csvs that can be read in as pandas tables would be great. Please reach out if you can do this and are not working on modeling itself.

**Comment by jules2689** [comment]
I'm not seeing age data in that link :hmmm-nod: @Cliff (edited) 

I did fine somewhat of an API: https://data.bls.gov/oes/#/occInd/One%20occupation%20for%20multiple%20industries

We could possible reverse-engineer that for easy-to-scrape data

**Comment by lgeorge-idm** [comment]
The data is already available as spreadsheets: https://www.bls.gov/oes/special.requests/oesm19ma.zip

**Comment by DMistry-IDM** [comment]
thank you @lgeorge-idm @jules2689 !

**Comment by lgeorge-idm** [comment]
Previous years are here (with links to download): https://www.bls.gov/oes/tables.htm

**Comment by lgeorge-idm** [comment]
@DMistry-IDM, also when do you need this data by?

**Comment by jules2689** [comment]
https://www.bls.gov/cps/cpsa2019.xlsx

This page has data for all industries at the (national?) level, including age. There are 55 spreadsheets in there.

**Comment by DMistry-IDM** [comment]
Can you post the page it's on? This simply downloads the file for me.Thanks.

**Comment by jules2689** [comment]
https://www.bls.gov/cps/tables.htm#empstat

I got it from the XLSX link:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/3074765/78616591-a20a9a80-7842-11ea-86ca-7eec6e87f3d1.png">

**Comment by DLukacevic-IDM** [comment]
Summary of what was done for US census "workplaces by county for 2015" (the request from Slack):

- Downloaded from 
https://www2.census.gov/programs-surveys/susb/guidance/special-tabulations/tab03.zip 
into "COVID-19/demographics/usa/_raw/census_workplaces_by_county_2015" dir. 
- Split by state, .csv stored into state folders: 
"COVID-19/demographics/usa/{state_name}/census/workplaces_by_county_2015.csv"

**Comment by lgeorge-idm** [comment]
@DMistry-IDM , can I close this?

**Comment by DMistry-IDM** [comment]
Yes.
