### ISSUE TITLE
UI - Support for interventions for specific time frames

### ISSUE THREAD

**Issue by sayers24** [InstituteforDiseaseModeling/covasim#71]
The user group wants to know the output when an intervention is implemented, lifted, then re-implemented at a future date.
Possible solution: A range slider for intervention-start-day with a "+" button to add a new point on the slider for intervention-end-day. The "+" button could then add a third point for a re-implementation day.

**Comment by ckerr-IDM** [comment]
@sayers24 yes this is supported

**Comment by deviozc** [comment]
Here's a quick mock I have using bootstrap style:
The UI control is base on the table.
The bar reflect the timeline of the intervention scenario.
Adding a new row would update the bar in the bottom.
Each scenario would have similar layout like this.

@cliffckerr @sayers24 please let me know if this works.
Multi handle slider would be another kind of control, but it needs some fine tuning to make it clear to users.

![image](https://user-images.githubusercontent.com/1392677/78748707-86c28c80-7921-11ea-9795-d657049771db.png)

**Comment by sayers24** [comment]
Very nice! I like the visual timeline. That would achieve the same thing as the slider approach would. The only benefit the slider would have is preventing invalid inputs (say if the first entry's end day is 25 and the next entry's start day is 20), which would make validation less complicated. The two concepts could easily be merged but both achieve what the user group wants.

@cliffckerr what are your thoughts?

**Comment by lgeorge-idm** [comment]
The visualized timeline looks great! It took me a couple of minutes to understand what it was actually communicating because humans are very bad at discerning fine details from **relative** size comparisons. I'm also not sure what the different colors are supposed to convey.

A Gantt chart would more accurately visualize the scenarios as we're really charting both transitions between scenario "effectiveness" across time and duration of each scenario's "effectiveness". An example with using a much more limited color palette.
![image](https://user-images.githubusercontent.com/43424134/78813648-2e6fa700-7982-11ea-8bb0-866995d8c88b.png)

**Comment by ckerr-IDM** [comment]
Great work guys! Yes I love @lgeorge-idm 's Gantt chart idea of one row per intervention -- this will be a great way of showing e.g. turn on social distancing, then turn on testing, then turn off social distancing, then turn off testing :)

**Comment by lgeorge-idm** [comment]
NOAA actually makes great (and interactive) use of this type of visualization: 
https://www.ngdc.noaa.gov/hazard/bpr/

It would be overkill for our purposes, but the ability to adjust the granularity of the timeline is pretty great.

**Comment by sayers24** [comment]
I think the colors were for the aggressiveness of the intervention. Do we still have this concept? I know the google doc had mild/moderate/aggressive within social distancing and the unified mockup had a percentage slider for effectiveness of a specific intervention

**Comment by ckerr-IDM** [comment]
I think we'll probably want to color by social distancing vs testing interventions mostly. We also don't want to give the implication that mild=good and aggressive=bad, which green and red could indicate.
