### ISSUE TITLE
Reorder UI for intervention controls 

### ISSUE THREAD

**Issue by sayers24** [InstituteforDiseaseModeling/covasim#72]
1 pick country/region
2 specify duration
3 specify interventions (from #71)
4 (optional) advanced - rest of params

**Comment by cliffckerr** [comment]
@deviozc Sorry for some reason I can't assign you, but I hereby assign you to this too :)

**Comment by cliffckerr** [comment]
This is an example of how to create an intervention changing beta at days 25 and 35:
```
import covasim as cv
pars = {
    'n_infected': 1000,
    'interventions': [cv.interventions.change_beta([25, 35], [0.5, 0.0])],
    }
sim = cv.Sim(pars=pars)
sim.run()
sim.plot()
```
@deviozc would you be able to start thinking about how to get these controls into the UI?

**Comment by deviozc** [comment]
Is demography currently supported in intervention?

**Comment by deviozc** [comment]
@sayers24 has some ideas from #71 
For MVP, does intervention UI need to take into account for different community and demography? eg. Social distancing applying to all communities but household, age-base social distancing, mask wearing only in workplace.

**Comment by cliffckerr** [comment]
@deviozc This should be in there, but not necessarily exposed to the user

**Comment by lgeorge-idm** [comment]
Launching from the scenario scheduler from #71  seems to be the right paradigm from which to start the user into developing their intervention campaign as opposed to picking the country.
All interventions have to be scheduled. It seems natural you start there and then add the other layers of configuration to that intervention. And then finish by inputting any additional global or "advanced" parameters.
It's also pretty natural in the sense that calendaring is very familiar when you have a drag, drop, and resize mechanism in place.

**Comment by ckerr-IDM** [comment]
@lgeorge-idm definitely not MVP, but if we could have your Gantt chart thing and the user could drag either end of the intervention to change the date -- 🤩

**Comment by lgeorge-idm** [comment]
@ckerr-IDM , fortunately the internet is awash with off the shelf gantt chart plugins, frameworks, etc. (e.g., https://github.com/neuronetio/gantt-elastic)  We may be able to repurpose that for our needs. @sayers24 and @deviozc , thoughts?

**Comment by deviozc** [comment]
Yeah, interactive gantt chart would work.
I'd start with using gantt chart to represent the intervention timeline first and see if we can make it interactive by this Friday.
