### ISSUE TITLE
[UI] Decide on list of Africa-specific interventions

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#74]
Building on the list of interventions listed here:

https://docs.google.com/document/d/1Q3-cLk9lo8Oizgs4JZTnqDCBjWu3oE93S42B9rSinfY/edit#

Provide a list of interventions that would be most useful to Africa CDC (e.g., different assumptions about social distancing and testing capacity)

**Comment by ckerr-IDM** [comment]
Will reopen as the need arises
