### ISSUE TITLE
Move checking bed_constraints to check_severe function

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#76]
We shoudl refactor death calculation with bed constraints (and other medical constraints, like ventilators). Right now death is determined in `infect` function, so at the time of infection. Beds can run out between infection and severe symptoms onset. We should check availability of beds when severe symptoms occur, and if that comes out false, modify probability of death.

Also, rather than determining death probability in `infect`, we should re-evaluate every epoch.

**Comment by ckerr-IDM** [comment]
This has been refactored so closing for now, can revisit if needed later
