### ISSUE TITLE
[UI] Include oxygen and other interventions

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#77]
Work from @aouedraogo and @lskrip-IDM 's recent report to get oxygen support and other health system parameters built into Covasim

**Comment by BHagedorn-IDM** [comment]
@cliffckerr what information do you need from us to parameterized? We have oxygen-dependent mortality rates by age. It is reasonable for now to assume that countries have zero available oxygen capacity. We know that is not true, but availability is limited and will be unlikely to be able to absorb excess demand from COVID.

**Comment by ckerr-IDM** [comment]
@BHagedorn-IDM yes just that would be good -- so i guess we need those mortality parameters, plus an `oxygen_capacity` parameter? cc @robynstuart @daniel-klein

**Comment by BHagedorn-IDM** [comment]
@aouedraogo has the latest mortality rates and will continue to update as we get new data. I have also put these items into the unified requirements document.

**Comment by ckerr-IDM** [comment]
Will reopen as the need arises
