### ISSUE TITLE
[UI] Improve frontend plotting

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#78]
Related to https://github.com/InstituteforDiseaseModeling/covasim/issues/51, we need to think about how to fix plotting. Here's how plotting looks on the BE:
![image](https://user-images.githubusercontent.com/3239256/78727371-54953880-78e9-11ea-9ad7-443789570c12.png)

At minimum we need to plot data, but other changes would be good too. Options:
* Keep Plotly and expand it
* Move to Altair
* Switch back to mpld3, so we can exactly reproduce backend figures

**Comment by cliffckerr** [comment]
@RomeshA @deviozc still can't assign you guys for some reason argh

**Comment by hamelsmu** [comment]
I believe this issue is a duplicate of https://github.com/InstituteforDiseaseModeling/covasim/issues/51

Perhaps close #51, @inc0 ?

**Comment by ckerr-IDM** [comment]
@hamelsmu related but not a duplicate, this is closed by #85 but altair would still be cool longer term (not MVP)

**Comment by cliffckerr** [comment]
Closed by #85
