### ISSUE TITLE
[UI] Finalize intervention options

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#82]
Decide which interventions will be supported by the webapp by Friday -- starting list:
* School closures
* Mild, moderate, and aggressive social distancing (or one social distancing intervention where the user specifies 0-100% effectiveness?)
* Community testing
* Contact tracing

Each of these need a start and end day and the user should be able to layer them on top of each other.

I think that's probably an MVP -- @daniel-klein @robynstuart @RomeshA @famulare what are your thoughts?

**Comment by lgeorge-idm** [comment]
Closing. If more categories of interventions need to be added, please open a new issue as an enhancement.
