### ISSUE TITLE
Add relative susceptibility

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#91]
Right now susceptibility is just boolean, either susceptible or not. We could model all sorts of interventions if we allow this to be float probability. That would allow us to, for example, modify beta based on person, for example, if we decide to force everyone who is above 70 to wear mask, we can modify their relative susceptibility and decrease risk of infection

**Comment by cliffckerr** [comment]
Closed by https://github.com/amath-idm/covasim/pull/321
